REMORA: ncutils::NCGroup Class Reference
ncutils::NCGroup Class Reference
Representation of a NetCDF group.
#include <NCInterface.H>
Public Member Functions
std::string name () const
Name of this group.
std::string full_name () const
Full name for this group.
int num_groups () const
Number of sub-groups within this group.
int num_dimensions () const
Number of dimensions in this group.
int num_variables () const
Number of variables within this group.
int num_attributes () const
Number of attributes within this group.
bool has_group (const std::string &) const
Check if a group exists.
bool has_dim (const std::string &) const
Check if a dimension exists by name.
bool has_var (const std::string &) const
Check if a variable exists by name.
bool has_attr (const std::string &) const
Check if an attribute exists.
NCGroup group (const std::string &) const
NCDim dim (const std::string &) const
Get the dimension instance by name.
NCVar var (const std::string &) const
Get the variable instance by name.
NCGroup def_group (const std::string &) const
Define new group.
NCDim def_dim (const std::string &, const size_t len) const
Define new dimension.
NCVar def_scalar (const std::string &name, const nc_type dtype) const
Define a scalar variable, i.e., 0-dimensional array.
NCVar def_array (const std::string &name, const nc_type dtype, const std::vector< std::string > &) const
Define an array.
NCVar def_var (const std::string &name, const nc_type dtype, const std::vector< std::string > &dnames) const
Define a variable (wrapper for def_array)
void put_attr (const std::string &name, const std::string &value) const
void put_attr (const std::string &name, const std::vector< double > &value) const
void put_attr (const std::string &name, const std::vector< float > &value) const
void put_attr (const std::string &name, const std::vector< int > &value) const
std::string get_attr (const std::string &name) const
void get_attr (const std::string &name, std::vector< double > &value) const
void get_attr (const std::string &name, std::vector< float > &value) const
void get_attr (const std::string &name, std::vector< int > &value) const
std::vector< NCGroup > all_groups () const
Return a list of all groups defined in this group.
std::vector< NCDim > all_dims () const
Return a list of all dimensions defined in this group.
std::vector< NCVar > all_vars () const
Return a list of all variables defined in this group.
void enter_def_mode () const
Enter definition mode (not needed for NetCDF4 format)
void exit_def_mode () const
Exit definition mode.
Public Attributes
const int ncid
Identifier used with NetCDF API calls.
Protected Member Functions
NCGroup (const int id)
NCGroup (const int id, const NCGroup *)
Detailed Description
Representation of a NetCDF group.
Constructor & Destructor Documentation
NCGroup() [1/2]
ncutils::NCGroup::NCGroup (const int id) inline protected
 : ncid(id) {}
Referenced by def_group(), and group().
NCGroup() [2/2]
ncutils::NCGroup::NCGroup (const int id, const NCGroup *) inline protected
 : ncid(id) {}
Member Function Documentation
all_dims()
std::vector< NCDim > ncutils::NCGroup::all_dims () const
Return a list of all dimensions defined in this group.
 {
     std::vector<NCDim> adims;
     int ndims = num_dimensions();
     adims.reserve(ndims);
     for (int i = 0; i < ndims; ++i) {
         adims.emplace_back(NCDim{ncid, i});
     }
     return adims;
 }
all_groups()
std::vector< NCGroup > ncutils::NCGroup::all_groups () const
Return a list of all groups defined in this group.
 {
     std::vector<NCGroup> grps;
     int ngrps = num_groups();
     // Empty list of groups return early without error
     if (ngrps < 1) return grps;
     std::vector<int> gids(ngrps);
     check_nc_error(nc_inq_grps(ncid, &ngrps, gids.data()));
     grps.reserve(ngrps);
     for (int i = 0; i < ngrps; ++i) grps.emplace_back(NCGroup(gids[i], this));
     return grps;
 }
all_vars()
std::vector< NCVar > ncutils::NCGroup::all_vars () const
Return a list of all variables defined in this group.
 {
     std::vector<NCVar> avars;
     int nvars = num_variables();
     avars.reserve(nvars);
     for (int i = 0; i < nvars; ++i) {
         avars.emplace_back(NCVar{ncid, i});
     }
     return avars;
 }
def_array()
NCVar ncutils::NCGroup::def_array (const std::string & name, const nc_type dtype, const std::vector< std::string > & dnames) const
Define an array.
 {
     int newid;
     int ndims = dnames.size();
     std::vector<int> dimids(ndims);
     for (int i = 0; i < ndims; ++i) {
         dimids[i] = dim(dnames[i]).dimid;
     }
     check_nc_error(
         nc_def_var(ncid, name.data(), dtype, ndims, dimids.data(), &newid));
     return NCVar{ncid, newid};
 }
Referenced by def_var().
def_dim()
NCDim ncutils::NCGroup::def_dim (const std::string & name, const size_t len) const
Define new dimension.
 {
     int newid;
     check_nc_error(nc_def_dim(ncid, name.data(), len, &newid));
     return NCDim{ncid, newid};
 }
def_group()
NCGroup ncutils::NCGroup::def_group (const std::string & name) const
Define new group.
 {
     int newid;
     check_nc_error(nc_def_grp(ncid, name.data(), &newid));
     return NCGroup(newid, this);
 }
def_scalar()
NCVar ncutils::NCGroup::def_scalar (const std::string & name, const nc_type dtype) const
Define a scalar variable, i.e., 0-dimensional array.
 {
     int newid;
     check_nc_error(nc_def_var(ncid, name.data(), dtype, 0, NULL, &newid));
     return NCVar{ncid, newid};
 }
def_var()
NCVar ncutils::NCGroup::def_var (const std::string & name, const nc_type dtype, const std::vector< std::string > & dnames) const inline
Define a variable (wrapper for def_array)
     {
         return def_array(name, dtype, dnames);
     }
dim()
NCDim ncutils::NCGroup::dim (const std::string & name) const
Get the dimension instance by name.
 {
     int newid;
     check_nc_error(nc_inq_dimid(ncid, name.data(), &newid));
     return NCDim{ncid, newid};
 }
Referenced by def_array().
enter_def_mode()
void ncutils::NCGroup::enter_def_mode () const
Enter definition mode (not needed for NetCDF4 format)
 {
     int ierr;
     ierr = nc_redef(ncid);
     // Ignore already in define mode error
     if (ierr == NC_EINDEFINE) return;
     // Handle all other errors
     check_nc_error(ierr);
 }
exit_def_mode()
void ncutils::NCGroup::exit_def_mode () const
Exit definition mode.
 { check_nc_error(nc_enddef(ncid)); }
full_name()
std::string ncutils::NCGroup::full_name () const
Full name for this group.
 {
     size_t nlen;
     std::vector<char> grpname;
     check_nc_error(nc_inq_grpname_full(ncid, &nlen, NULL));
     grpname.resize(nlen);
     check_nc_error(nc_inq_grpname_full(ncid, &nlen, grpname.data()));
     return std::string{grpname.begin(), grpname.end()};
 }
get_attr() [1/4]
std::string ncutils::NCGroup::get_attr (const std::string & name) const
 {
     size_t lenp;
     std::vector<char> aval;
     check_nc_error(nc_inq_attlen(ncid, NC_GLOBAL, name.data(), &lenp));
     aval.resize(lenp);
     check_nc_error(nc_get_att_text(ncid, NC_GLOBAL, name.data(), aval.data()));
     return std::string{aval.begin(), aval.end()};
 }
get_attr() [2/4]
void ncutils::NCGroup::get_attr (const std::string & name, std::vector< double > & value) const
 {
     size_t lenp;
     check_nc_error(nc_inq_attlen(ncid, NC_GLOBAL, name.data(), &lenp));
     values.resize(lenp);
     check_nc_error(
         nc_get_att_double(ncid, NC_GLOBAL, name.data(), values.data()));
 }
get_attr() [3/4]
void ncutils::NCGroup::get_attr (const std::string & name, std::vector< float > & value) const
 {
     size_t lenp;
     check_nc_error(nc_inq_attlen(ncid, NC_GLOBAL, name.data(), &lenp));
     values.resize(lenp);
     check_nc_error(
         nc_get_att_float(ncid, NC_GLOBAL, name.data(), values.data()));
 }
get_attr() [4/4]
void ncutils::NCGroup::get_attr (const std::string & name, std::vector< int > & value) const
 {
     size_t lenp;
     check_nc_error(nc_inq_attlen(ncid, NC_GLOBAL, name.data(), &lenp));
     values.resize(lenp);
     check_nc_error(nc_get_att_int(ncid, NC_GLOBAL, name.data(), values.data()));
 }
group()
NCGroup ncutils::NCGroup::group (const std::string & name) const
Get the group by name
Throws error if the group doesn't exist, use has_group to check
 {
     int newid;
     check_nc_error(nc_inq_ncid(ncid, name.data(), &newid));
     return NCGroup(newid, this);
 }
has_attr()
bool ncutils::NCGroup::has_attr (const std::string & name) const
Check if an attribute exists.
 {
     int ierr;
     size_t lenp;
     ierr = nc_inq_att(ncid, NC_GLOBAL, name.data(), NULL, &lenp);
     return (ierr == NC_NOERR);
 }
has_dim()
bool ncutils::NCGroup::has_dim (const std::string & name) const
Check if a dimension exists by name.
 {
     int ierr = nc_inq_dimid(ncid, name.data(), NULL);
     return (ierr == NC_NOERR);
 }
has_group()
bool ncutils::NCGroup::has_group (const std::string & name) const
Check if a group exists.
 {
     int ierr = nc_inq_ncid(ncid, name.data(), NULL);
     return (ierr == NC_NOERR);
 }
has_var()
bool ncutils::NCGroup::has_var (const std::string & name) const
Check if a variable exists by name.
 {
     int ierr = nc_inq_varid(ncid, name.data(), NULL);
     return (ierr == NC_NOERR);
 }
name()
std::string ncutils::NCGroup::name () const
Name of this group.
 {
     size_t nlen;
     std::vector<char> grpname;
     check_nc_error(nc_inq_grpname_len(ncid, &nlen));
     grpname.resize(nlen + 1);
     check_nc_error(nc_inq_grpname(ncid, grpname.data()));
     return std::string{grpname.begin(), grpname.end()};
 }
Referenced by ncutils::NCFile::create(), ncutils::NCFile::create_par(), def_array(), def_dim(), def_group(), def_scalar(), def_var(), dim(), get_attr(), group(), has_attr(), has_dim(), has_group(), has_var(), ncutils::NCFile::open(), ncutils::NCFile::open_par(), put_attr(), and var().
num_attributes()
int ncutils::NCGroup::num_attributes () const
Number of attributes within this group.
 {
     int nattrs;
     check_nc_error(nc_inq(ncid, NULL, NULL, &nattrs, NULL));
     return nattrs;
 }
num_dimensions()
int ncutils::NCGroup::num_dimensions () const
Number of dimensions in this group.
 {
     int ndims;
     check_nc_error(nc_inq(ncid, &ndims, NULL, NULL, NULL));
     return ndims;
 }
Referenced by all_dims().
num_groups()
int ncutils::NCGroup::num_groups () const
Number of sub-groups within this group.
 {
     int ngrps;
     check_nc_error(nc_inq_grps(ncid, &ngrps, NULL));
     return ngrps;
 }
Referenced by all_groups().
num_variables()
int ncutils::NCGroup::num_variables () const
Number of variables within this group.
 {
     int nvars;
     check_nc_error(nc_inq(ncid, NULL, &nvars, NULL, NULL));
     return nvars;
 }
Referenced by all_vars().
put_attr() [1/4]
void ncutils::NCGroup::put_attr (const std::string & name, const std::string & value) const
 {
     check_nc_error(nc_put_att_text(
         ncid, NC_GLOBAL, name.data(), value.size(), value.data()));
 }
put_attr() [2/4]
void ncutils::NCGroup::put_attr (const std::string & name, const std::vector< double > & value) const
 {
     check_nc_error(nc_put_att_double(
         ncid, NC_GLOBAL, name.data(), NC_DOUBLE, value.size(), value.data()));
 }
put_attr() [3/4]
void ncutils::NCGroup::put_attr (const std::string & name, const std::vector< float > & value) const
 {
     check_nc_error(nc_put_att_float(
         ncid, NC_GLOBAL, name.data(), NC_FLOAT, value.size(), value.data()));
 }
put_attr() [4/4]
void ncutils::NCGroup::put_attr (const std::string & name, const std::vector< int > & value) const
 {
     check_nc_error(nc_put_att_int(
         ncid, NC_GLOBAL, name.data(), NC_INT, value.size(), value.data()));
 }
var()
NCVar ncutils::NCGroup::var (const std::string & name) const
Get the variable instance by name.
 {
     int varid;
     check_nc_error(nc_inq_varid(ncid, name.data(), &varid));
     return NCVar{ncid, varid};
 }
Member Data Documentation
ncid
const int ncutils::NCGroup::ncid
Identifier used with NetCDF API calls.
Referenced by all_dims(), all_groups(), all_vars(), ncutils::NCFile::close(), ncutils::NCFile::create(), ncutils::NCFile::create_par(), def_array(), def_dim(), def_group(), def_scalar(), dim(), enter_def_mode(), exit_def_mode(), full_name(), get_attr(), group(), has_attr(), has_dim(), has_group(), has_var(), name(), num_attributes(), num_dimensions(), num_groups(), num_variables(), ncutils::NCFile::open(), ncutils::NCFile::open_par(), put_attr(), var(), and ncutils::NCFile::~NCFile().
The documentation for this class was generated from the following files:
/home/runner/work/REMORA/REMORA/Source/IO/NCInterface.H
/home/runner/work/REMORA/REMORA/Source/IO/NCInterface.cpp