var dir_759b90b1f3ea3c20e13693c83a3534b7 =
[
    [ "REMORA_Advance.cpp", "REMORA__Advance_8cpp.html", null ],
    [ "REMORA_advance_2d.cpp", "REMORA__advance__2d_8cpp.html", null ],
    [ "REMORA_advance_2d_onestep.cpp", "REMORA__advance__2d__onestep_8cpp.html", null ],
    [ "REMORA_advance_3d.cpp", "REMORA__advance__3d_8cpp.html", null ],
    [ "REMORA_advance_3d_ml.cpp", "REMORA__advance__3d__ml_8cpp.html", null ],
    [ "REMORA_ComputeTimestep.cpp", "REMORA__ComputeTimestep_8cpp.html", null ],
    [ "REMORA_coriolis.cpp", "REMORA__coriolis_8cpp.html", null ],
    [ "REMORA_prestep.cpp", "REMORA__prestep_8cpp.html", null ],
    [ "REMORA_prestep_diffusion.cpp", "REMORA__prestep__diffusion_8cpp.html", null ],
    [ "REMORA_prestep_t_advection.cpp", "REMORA__prestep__t__advection_8cpp.html", null ],
    [ "REMORA_prsgrd.cpp", "REMORA__prsgrd_8cpp.html", null ],
    [ "REMORA_rho_eos.cpp", "REMORA__rho__eos_8cpp.html", null ],
    [ "REMORA_rhs_t_3d.cpp", "REMORA__rhs__t__3d_8cpp.html", null ],
    [ "REMORA_rhs_uv_2d.cpp", "REMORA__rhs__uv__2d_8cpp.html", null ],
    [ "REMORA_rhs_uv_3d.cpp", "REMORA__rhs__uv__3d_8cpp.html", null ],
    [ "REMORA_set_weights.cpp", "REMORA__set__weights_8cpp.html", null ],
    [ "REMORA_setup_step.cpp", "REMORA__setup__step_8cpp.html", null ],
    [ "REMORA_t3dmix.cpp", "REMORA__t3dmix_8cpp.html", null ],
    [ "REMORA_TimeStep.cpp", "REMORA__TimeStep_8cpp.html", null ],
    [ "REMORA_TimeStepML.cpp", "REMORA__TimeStepML_8cpp.html", null ],
    [ "REMORA_update_massflux_3d.cpp", "REMORA__update__massflux__3d_8cpp.html", null ],
    [ "REMORA_uv3dmix.cpp", "REMORA__uv3dmix_8cpp.html", null ],
    [ "REMORA_vert_mean_3d.cpp", "REMORA__vert__mean__3d_8cpp.html", null ],
    [ "REMORA_vert_visc_3d.cpp", "REMORA__vert__visc__3d_8cpp.html", null ]
];