ROMSX: derived Namespace Reference
derived Namespace Reference
Functions
void romsx_derrhodivide (const amrex::Box &bx, amrex::FArrayBox &dromsxab, const amrex::FArrayBox &datfab, const int scalar_index)
void romsx_dernull (const amrex::Box &, amrex::FArrayBox &, int, int, const amrex::FArrayBox &, const amrex::Geometry &, amrex::Real, const int *, const int)
void romsx_derscalar (const amrex::Box &bx, amrex::FArrayBox &dromsxab, int, int, const amrex::FArrayBox &datfab, const amrex::Geometry &, amrex::Real, const int *, const int)
void romsx_derKE (const amrex::Box &bx, amrex::FArrayBox &dromsxab, int, int, const amrex::FArrayBox &datfab, const amrex::Geometry &, amrex::Real, const int *, const int)
void romsx_derQKE (const amrex::Box &bx, amrex::FArrayBox &dromsxab, int, int, const amrex::FArrayBox &datfab, const amrex::Geometry &, amrex::Real, const int *, const int)
void romsx_deromega (const amrex::Box &bx, amrex::FArrayBox &dromsxab, int, int, const amrex::FArrayBox &datfab, const amrex::Geometry &, amrex::Real, const int *, const int)
Function Documentation
romsx_derKE()
void derived::romsx_derKE (const amrex::Box & bx, amrex::FArrayBox & dromsxab, int , int , const amrex::FArrayBox & datfab, const amrex::Geometry & , amrex::Real , const int * , const int)
 {
   romsx_derrhodivide(bx, dromsxab, datfab, RhoKE_comp);
 }
Referenced by ROMSX::WritePlotFile().
romsx_dernull()
void derived::romsx_dernull (const amrex::Box & , amrex::FArrayBox & , int , int , const amrex::FArrayBox & , const amrex::Geometry & , amrex::Real , const int * , const int)
 {
   // This routine does nothing -- we use it as a placeholder.
 }
Referenced by ROMSX::WritePlotFile().
romsx_deromega()
void derived::romsx_deromega (const amrex::Box & bx, amrex::FArrayBox & dromsxab, int , int , const amrex::FArrayBox & datfab, const amrex::Geometry & , amrex::Real , const int * , const int)
 {
   romsx_derrhodivide(bx, dromsxab, datfab, Omega_comp);
 }
romsx_derQKE()
void derived::romsx_derQKE (const amrex::Box & bx, amrex::FArrayBox & dromsxab, int , int , const amrex::FArrayBox & datfab, const amrex::Geometry & , amrex::Real , const int * , const int)
 {
   romsx_derrhodivide(bx, dromsxab, datfab, RhoQKE_comp);
 }
Referenced by ROMSX::WritePlotFile().
romsx_derrhodivide()
void derived::romsx_derrhodivide (const amrex::Box & bx, amrex::FArrayBox & dromsxab, const amrex::FArrayBox & datfab, const int scalar_index)
 {
   // This routine divides any cell-centered conserved quantity by density
   auto const dat = datfab.array();
   auto primitive  = dromsxab.array();
   amrex::ParallelFor(bx, [=] AMREX_GPU_DEVICE(int i, int j, int k) noexcept {
     const amrex::Real rho       = dat(i, j, k, Rho_comp);
     const amrex::Real conserved = dat(i, j, k, scalar_index);
     primitive(i,j,k) = conserved / rho;
   });
 }
Referenced by romsx_derKE(), romsx_deromega(), romsx_derQKE(), and romsx_derscalar().
romsx_derscalar()
void derived::romsx_derscalar (const amrex::Box & bx, amrex::FArrayBox & dromsxab, int , int , const amrex::FArrayBox & datfab, const amrex::Geometry & , amrex::Real , const int * , const int)
 {
   romsx_derrhodivide(bx, dromsxab, datfab, RhoScalar_comp);
 }
Referenced by ROMSX::WritePlotFile().