REMORA: amrex Namespace Reference
amrex Namespace Reference
Functions
const char * buildInfoGetBuildDate ()
const char * buildInfoGetComp ()
const char * buildInfoGetGitHash (int i)
const char * buildInfoGetCompVersion ()
Function Documentation
buildInfoGetBuildDate()
const char * amrex::buildInfoGetBuildDate ()
Referenced by REMORA::writeBuildInfo(), and REMORA::writeJobInfo().
buildInfoGetComp()
const char * amrex::buildInfoGetComp ()
Referenced by REMORA::writeBuildInfo(), and REMORA::writeJobInfo().
buildInfoGetCompVersion()
const char * amrex::buildInfoGetCompVersion ()
Referenced by REMORA::writeBuildInfo(), and REMORA::writeJobInfo().
buildInfoGetGitHash()
const char * amrex::buildInfoGetGitHash (int i)
Referenced by REMORA::REMORA(), REMORA::REMORA(), REMORA::writeBuildInfo(), and REMORA::writeJobInfo().