REMORA: BCVars Namespace Reference
BCVars Namespace Reference
Boundary fill types.
Functions
int xvel_bc (int ncons) noexcept
int yvel_bc (int ncons) noexcept
int zvel_bc (int ncons) noexcept
int ubar_bc (int ncons) noexcept
int vbar_bc (int ncons) noexcept
int zeta_bc (int ncons) noexcept
int tke_bc (int ncons) noexcept
int foextrap_periodic_bc (int ncons) noexcept
int foextrap_bc (int ncons) noexcept
int u2d_simple_bc (int ncons) noexcept
int v2d_simple_bc (int ncons) noexcept
int NumTypes (int ncons) noexcept
Variables
static constexpr int cons_bc = 0
static constexpr int Temp_bc_comp = 0
static constexpr int Salt_bc_comp = 1
static constexpr int Scalar_bc_comp = 2
Detailed Description
Boundary fill types.
Function Documentation
foextrap_bc()
int BCVars::foextrap_bc (int ncons) inline noexcept
Definition at line 37 of file REMORA_IndexDefines.H.
Referenced by REMORA::foextrap_bc(), REMORAPhysBCFunct::impose_cons_bcs(), REMORAPhysBCFunct::impose_xvel_bcs(), REMORAPhysBCFunct::impose_yvel_bcs(), REMORAPhysBCFunct::impose_zvel_bcs(), and REMORAPhysBCFunct::operator()().
foextrap_periodic_bc()
int BCVars::foextrap_periodic_bc (int ncons) inline noexcept
Definition at line 36 of file REMORA_IndexDefines.H.
Referenced by REMORA::foextrap_periodic_bc().
NumTypes()
int BCVars::NumTypes (int ncons) inline noexcept
Definition at line 40 of file REMORA_IndexDefines.H.
Referenced by REMORA::init_bcs(), and REMORA::num_bc_vars().
tke_bc()
int BCVars::tke_bc (int ncons) inline noexcept
Definition at line 35 of file REMORA_IndexDefines.H.
Referenced by REMORA::tke_bc().
u2d_simple_bc()
int BCVars::u2d_simple_bc (int ncons) inline noexcept
Definition at line 38 of file REMORA_IndexDefines.H.
Referenced by REMORA::u2d_simple_bc().
ubar_bc()
int BCVars::ubar_bc (int ncons) inline noexcept
Definition at line 32 of file REMORA_IndexDefines.H.
Referenced by REMORA::ubar_bc().
v2d_simple_bc()
int BCVars::v2d_simple_bc (int ncons) inline noexcept
Definition at line 39 of file REMORA_IndexDefines.H.
Referenced by REMORA::v2d_simple_bc().
vbar_bc()
int BCVars::vbar_bc (int ncons) inline noexcept
Definition at line 33 of file REMORA_IndexDefines.H.
Referenced by REMORA::vbar_bc().
xvel_bc()
int BCVars::xvel_bc (int ncons) inline noexcept
Definition at line 29 of file REMORA_IndexDefines.H.
Referenced by REMORA::xvel_bc().
yvel_bc()
int BCVars::yvel_bc (int ncons) inline noexcept
Definition at line 30 of file REMORA_IndexDefines.H.
Referenced by REMORA::yvel_bc().
zeta_bc()
int BCVars::zeta_bc (int ncons) inline noexcept
Definition at line 34 of file REMORA_IndexDefines.H.
Referenced by REMORAPhysBCFunct::impose_cons_bcs(), and REMORA::zeta_bc().
zvel_bc()
int BCVars::zvel_bc (int ncons) inline noexcept
Definition at line 31 of file REMORA_IndexDefines.H.
Referenced by REMORA::zvel_bc().
Variable Documentation
cons_bc
constexpr int BCVars::cons_bc = 0 static constexpr
Definition at line 24 of file REMORA_IndexDefines.H.
Referenced by REMORA::advance_3d(), REMORA::ErrorEst(), REMORA::init_bcs(), REMORA::InitData(), REMORA::MakeNewLevelFromCoarse(), REMORA::RemakeLevel(), REMORA::set_bathymetry(), REMORA::set_coriolis(), REMORA::set_init_data_averaged_down(), REMORA::set_zeta(), and REMORA::setup_step().
Salt_bc_comp
constexpr int BCVars::Salt_bc_comp = 1 static constexpr
Definition at line 26 of file REMORA_IndexDefines.H.
Referenced by REMORA::init_bcs().
Scalar_bc_comp
constexpr int BCVars::Scalar_bc_comp = 2 static constexpr
Definition at line 27 of file REMORA_IndexDefines.H.
Referenced by REMORA::init_bcs().
Temp_bc_comp
constexpr int BCVars::Temp_bc_comp = 0 static constexpr
Definition at line 25 of file REMORA_IndexDefines.H.
Referenced by REMORA::init_bcs(), REMORA::init_only(), and REMORA::MakeNewLevelFromCoarse().