REMORA: /home/runner/work/REMORA/REMORA/Source/REMORA_Constants.H File Reference
REMORA_Constants.H File Reference
#include <AMReX_REAL.H>
Variables
constexpr amrex::Real PI = amrex::Real(3.14159265358979323846264338327950288)
constexpr amrex::Real Cp = amrex::Real(3985.0)
constexpr amrex::Real Csolar = amrex::Real(1353.0)
constexpr amrex::Real Eradius = amrex::Real(6371315.0)
constexpr amrex::Real StefBo = amrex::Real(5.670374419e-8)
constexpr amrex::Real emmiss = amrex::Real(0.97)
constexpr amrex::Real rhow = amrex::Real(1000.0)
constexpr amrex::Real g = amrex::Real(9.80665)
constexpr amrex::Real vonKar = amrex::Real(0.41)
constexpr amrex::Real blk_Cpa = amrex::Real(1004.67)
constexpr amrex::Real blk_Cpw = amrex::Real(4000.0)
constexpr amrex::Real blk_Rgas = amrex::Real(287.1)
constexpr amrex::Real blk_Zabl = amrex::Real(600.0)
constexpr amrex::Real blk_beta = amrex::Real(1.2)
constexpr amrex::Real blk_dter = amrex::Real(0.3)
constexpr amrex::Real blk_tcw = amrex::Real(0.6)
constexpr amrex::Real blk_visw = amrex::Real(0.000001)
constexpr amrex::Real A00 = amrex::Real(1.909256e+04)
constexpr amrex::Real A01 = amrex::Real(2.098925e+02)
constexpr amrex::Real A02 = amrex::Real(-3.041638e+00)
constexpr amrex::Real A03 = amrex::Real(-1.852732e-03)
constexpr amrex::Real A04 = amrex::Real(-1.361629e-05)
constexpr amrex::Real B00 = amrex::Real(1.044077e+02)
constexpr amrex::Real B01 = amrex::Real(-6.500517e+00)
constexpr amrex::Real B02 = amrex::Real(1.553190e-01)
constexpr amrex::Real B03 = amrex::Real(2.326469e-04)
constexpr amrex::Real D00 = amrex::Real(-5.587545e+00)
constexpr amrex::Real D01 = amrex::Real(7.390729e-01)
constexpr amrex::Real D02 = amrex::Real(-1.909078e-02)
constexpr amrex::Real E00 = amrex::Real(4.721788e-01)
constexpr amrex::Real E01 = amrex::Real(1.028859e-02)
constexpr amrex::Real E02 = amrex::Real(-2.512549e-04)
constexpr amrex::Real E03 = amrex::Real(-5.939910e-07)
constexpr amrex::Real F00 = amrex::Real(-1.571896e-02)
constexpr amrex::Real F01 = amrex::Real(-2.598241e-04)
constexpr amrex::Real F02 = amrex::Real(7.267926e-06)
constexpr amrex::Real G00 = amrex::Real(2.042967e-03)
constexpr amrex::Real G01 = amrex::Real(1.045941e-05)
constexpr amrex::Real G02 = amrex::Real(-5.782165e-10)
constexpr amrex::Real G03 = amrex::Real(1.296821e-07)
constexpr amrex::Real H00 = amrex::Real(-2.595994e-07)
constexpr amrex::Real H01 = amrex::Real(-1.248266e-09)
constexpr amrex::Real H02 = amrex::Real(-3.508914e-09)
constexpr amrex::Real Q00 = amrex::Real(9.99842594e+02)
constexpr amrex::Real Q01 = amrex::Real(6.793952e-02)
constexpr amrex::Real Q02 = amrex::Real(-9.095290e-03)
constexpr amrex::Real Q03 = amrex::Real(1.001685e-04)
constexpr amrex::Real Q04 = amrex::Real(-1.120083e-06)
constexpr amrex::Real Q05 = amrex::Real(6.536332e-09)
constexpr amrex::Real U00 = amrex::Real(8.24493e-01)
constexpr amrex::Real U01 = amrex::Real(-4.08990e-03)
constexpr amrex::Real U02 = amrex::Real(7.64380e-05)
constexpr amrex::Real U03 = amrex::Real(-8.24670e-07)
constexpr amrex::Real U04 = amrex::Real(5.38750e-09)
constexpr amrex::Real V00 = amrex::Real(-5.72466e-03)
constexpr amrex::Real V01 = amrex::Real(1.02270e-04)
constexpr amrex::Real V02 = amrex::Real(-1.65460e-06)
constexpr amrex::Real W00 = amrex::Real(4.8314e-04)
Variable Documentation
A00
constexpr amrex::Real A00 = amrex::Real(1.909256e+04) constexpr
Definition at line 52 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
A01
constexpr amrex::Real A01 = amrex::Real(2.098925e+02) constexpr
Definition at line 53 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
A02
constexpr amrex::Real A02 = amrex::Real(-3.041638e+00) constexpr
Definition at line 54 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
A03
constexpr amrex::Real A03 = amrex::Real(-1.852732e-03) constexpr
Definition at line 55 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
A04
constexpr amrex::Real A04 = amrex::Real(-1.361629e-05) constexpr
Definition at line 56 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
B00
constexpr amrex::Real B00 = amrex::Real(1.044077e+02) constexpr
Definition at line 57 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
B01
constexpr amrex::Real B01 = amrex::Real(-6.500517e+00) constexpr
Definition at line 58 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
B02
constexpr amrex::Real B02 = amrex::Real(1.553190e-01) constexpr
Definition at line 59 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
B03
constexpr amrex::Real B03 = amrex::Real(2.326469e-04) constexpr
Definition at line 60 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
blk_beta
constexpr amrex::Real blk_beta = amrex::Real(1.2) constexpr
Definition at line 40 of file REMORA_Constants.H.
Referenced by REMORA::bulk_fluxes().
blk_Cpa
constexpr amrex::Real blk_Cpa = amrex::Real(1004.67) constexpr
Definition at line 36 of file REMORA_Constants.H.
Referenced by REMORA::bulk_fluxes().
blk_Cpw
constexpr amrex::Real blk_Cpw = amrex::Real(4000.0) constexpr
Definition at line 37 of file REMORA_Constants.H.
Referenced by REMORA::bulk_fluxes().
blk_dter
constexpr amrex::Real blk_dter = amrex::Real(0.3) constexpr
Definition at line 41 of file REMORA_Constants.H.
blk_Rgas
constexpr amrex::Real blk_Rgas = amrex::Real(287.1) constexpr
Definition at line 38 of file REMORA_Constants.H.
Referenced by REMORA::bulk_fluxes().
blk_tcw
constexpr amrex::Real blk_tcw = amrex::Real(0.6) constexpr
Definition at line 42 of file REMORA_Constants.H.
blk_visw
constexpr amrex::Real blk_visw = amrex::Real(0.000001) constexpr
Definition at line 43 of file REMORA_Constants.H.
blk_Zabl
constexpr amrex::Real blk_Zabl = amrex::Real(600.0) constexpr
Definition at line 39 of file REMORA_Constants.H.
Referenced by REMORA::bulk_fluxes().
Cp
constexpr amrex::Real Cp = amrex::Real(3985.0) constexpr
Definition at line 10 of file REMORA_Constants.H.
Referenced by REMORA::bulk_fluxes(), and REMORA::WriteNCPlotFile_which().
Csolar
constexpr amrex::Real Csolar = amrex::Real(1353.0) constexpr
Definition at line 11 of file REMORA_Constants.H.
D00
constexpr amrex::Real D00 = amrex::Real(-5.587545e+00) constexpr
Definition at line 61 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
D01
constexpr amrex::Real D01 = amrex::Real(7.390729e-01) constexpr
Definition at line 62 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
D02
constexpr amrex::Real D02 = amrex::Real(-1.909078e-02) constexpr
Definition at line 63 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
E00
constexpr amrex::Real E00 = amrex::Real(4.721788e-01) constexpr
Definition at line 64 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
E01
constexpr amrex::Real E01 = amrex::Real(1.028859e-02) constexpr
Definition at line 65 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
E02
constexpr amrex::Real E02 = amrex::Real(-2.512549e-04) constexpr
Definition at line 66 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
E03
constexpr amrex::Real E03 = amrex::Real(-5.939910e-07) constexpr
Definition at line 67 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
emmiss
constexpr amrex::Real emmiss = amrex::Real(0.97) constexpr
Definition at line 14 of file REMORA_Constants.H.
Referenced by REMORA::bulk_fluxes().
Eradius
constexpr amrex::Real Eradius = amrex::Real(6371315.0) constexpr
Definition at line 12 of file REMORA_Constants.H.
F00
constexpr amrex::Real F00 = amrex::Real(-1.571896e-02) constexpr
Definition at line 68 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
F01
constexpr amrex::Real F01 = amrex::Real(-2.598241e-04) constexpr
Definition at line 69 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
F02
constexpr amrex::Real F02 = amrex::Real(7.267926e-06) constexpr
Definition at line 70 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
g
constexpr amrex::Real g = amrex::Real(9.80665) constexpr
Definition at line 16 of file REMORA_Constants.H.
Referenced by REMORA::advance_2d(), REMORA::bulk_fluxes(), REMORA::fill_from_bdyfiles(), REMORA::lin_eos(), REMORA::nonlin_eos(), and REMORA::prsgrd().
G00
constexpr amrex::Real G00 = amrex::Real(2.042967e-03) constexpr
Definition at line 71 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
G01
constexpr amrex::Real G01 = amrex::Real(1.045941e-05) constexpr
Definition at line 72 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
G02
constexpr amrex::Real G02 = amrex::Real(-5.782165e-10) constexpr
Definition at line 73 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
G03
constexpr amrex::Real G03 = amrex::Real(1.296821e-07) constexpr
Definition at line 74 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
H00
constexpr amrex::Real H00 = amrex::Real(-2.595994e-07) constexpr
Definition at line 75 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
H01
constexpr amrex::Real H01 = amrex::Real(-1.248266e-09) constexpr
Definition at line 76 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
H02
constexpr amrex::Real H02 = amrex::Real(-3.508914e-09) constexpr
Definition at line 77 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
PI
constexpr amrex::Real PI = amrex::Real(3.14159265358979323846264338327950288) constexpr
Definition at line 6 of file REMORA_Constants.H.
Referenced by REMORA::bulk_psit(), and REMORA::bulk_psiu().
Q00
constexpr amrex::Real Q00 = amrex::Real(9.99842594e+02) constexpr
Definition at line 78 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
Q01
constexpr amrex::Real Q01 = amrex::Real(6.793952e-02) constexpr
Definition at line 79 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
Q02
constexpr amrex::Real Q02 = amrex::Real(-9.095290e-03) constexpr
Definition at line 80 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
Q03
constexpr amrex::Real Q03 = amrex::Real(1.001685e-04) constexpr
Definition at line 81 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
Q04
constexpr amrex::Real Q04 = amrex::Real(-1.120083e-06) constexpr
Definition at line 82 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
Q05
constexpr amrex::Real Q05 = amrex::Real(6.536332e-09) constexpr
Definition at line 83 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
rhow
constexpr amrex::Real rhow = amrex::Real(1000.0) constexpr
Definition at line 15 of file REMORA_Constants.H.
Referenced by REMORA::bulk_fluxes(), and REMORA::set_zeta_to_Ztavg().
StefBo
constexpr amrex::Real StefBo = amrex::Real(5.670374419e-8) constexpr
Definition at line 13 of file REMORA_Constants.H.
Referenced by REMORA::bulk_fluxes().
U00
constexpr amrex::Real U00 = amrex::Real(8.24493e-01) constexpr
Definition at line 84 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
U01
constexpr amrex::Real U01 = amrex::Real(-4.08990e-03) constexpr
Definition at line 85 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
U02
constexpr amrex::Real U02 = amrex::Real(7.64380e-05) constexpr
Definition at line 86 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
U03
constexpr amrex::Real U03 = amrex::Real(-8.24670e-07) constexpr
Definition at line 87 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
U04
constexpr amrex::Real U04 = amrex::Real(5.38750e-09) constexpr
Definition at line 88 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
V00
constexpr amrex::Real V00 = amrex::Real(-5.72466e-03) constexpr
Definition at line 89 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
V01
constexpr amrex::Real V01 = amrex::Real(1.02270e-04) constexpr
Definition at line 90 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
V02
constexpr amrex::Real V02 = amrex::Real(-1.65460e-06) constexpr
Definition at line 91 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().
vonKar
constexpr amrex::Real vonKar = amrex::Real(0.41) constexpr
Definition at line 17 of file REMORA_Constants.H.
Referenced by REMORA::bulk_fluxes(), REMORA::gls_corrector(), and REMORA::setup_step().
W00
constexpr amrex::Real W00 = amrex::Real(4.8314e-04) constexpr
Definition at line 92 of file REMORA_Constants.H.
Referenced by REMORA::nonlin_eos().