REMORA: /home/runner/work/REMORA/REMORA/Source/Prob/REMORA_InitAnalyticProb_Upwelling_ML.H File Reference
REMORA_InitAnalyticProb_Upwelling_ML.H File Reference
Functions
ParmParse pp_prob ("remora.prob")
pp_prob query ("u_0", u_0)
pp_prob query ("v_0", v_0)
pp_prob query ("z0", z0)
pp_prob query ("zRef", zRef)
pp_prob query ("velRef", velRef)
for (MFIter mfi(mf_cons, TilingIfNotGPU());mfi.isValid();++mfi)
Variables
Real u_0 = Real(0.0)
Real v_0 = Real(0.0)
Real z0 = Real(0.1)
Real zRef = Real(80.)
Real velRef = Real(0.0)
bool l_use_salt = m_solverChoice.use_salt
auto T0 = m_solverChoice.T0
auto S0 = m_solverChoice.S0
Function Documentation
for()
for (MFIter mfi(mf_cons, TilingIfNotGPU());mfi.isValid();++ mfi)
Definition at line 14 of file REMORA_InitAnalyticProb_Upwelling_ML.H.
pp_prob()
ParmParse pp_prob ("remora.prob")
query() [1/5]
pp_prob query ("u_0" , u_0)
query() [2/5]
pp_prob query ("v_0" , v_0)
query() [3/5]
pp_prob query ("velRef" , velRef)
query() [4/5]
pp_prob query ("z0" , z0)
query() [5/5]
pp_prob query ("zRef" , zRef)
Variable Documentation
l_use_salt
bool l_use_salt = m_solverChoice.use_salt
Definition at line 9 of file REMORA_InitAnalyticProb_Upwelling_ML.H.
Referenced by for().
S0
auto S0 = m_solverChoice.S0
Definition at line 12 of file REMORA_InitAnalyticProb_Upwelling_ML.H.
Referenced by for().
T0
auto T0 = m_solverChoice.T0
Definition at line 11 of file REMORA_InitAnalyticProb_Upwelling_ML.H.
Referenced by for().
u_0
Real u_0 = Real(0.0)
Definition at line 3 of file REMORA_InitAnalyticProb_Upwelling_ML.H.
Referenced by for().
v_0
Real v_0 = Real(0.0)
Definition at line 4 of file REMORA_InitAnalyticProb_Upwelling_ML.H.
velRef
Real velRef = Real(0.0)
Definition at line 7 of file REMORA_InitAnalyticProb_Upwelling_ML.H.
Referenced by for().
z0
Real z0 = Real(0.1)
Definition at line 5 of file REMORA_InitAnalyticProb_Upwelling_ML.H.
Referenced by for().
zRef
Real zRef = Real(80.)
Definition at line 6 of file REMORA_InitAnalyticProb_Upwelling_ML.H.
Referenced by for().