REMORA: /home/runner/work/REMORA/REMORA/Source/Prob/REMORA_InitAnalyticSMFlux_ChannelTest.H File Reference
REMORA_InitAnalyticSMFlux_ChannelTest.H File Reference
Functions
mf_sustr setVal (windamp_u)
mf_svstr setVal (0.0_rt)
Variables
Real time = remora.get_t_old(lev)
Real tdays =time/Real(24.0*60.0*60.0)
Real dstart =0.0_rt
Real userval =0.01_rt
Real mf_fcor =1.0e-4_rt
Real windamp_u = userval*std::sin(0.9_rt*mf_fcor*86400.0_rt*(tdays-dstart))/m_solverChoice.rho0
Function Documentation
setVal() [1/2]
mf_svstr setVal (0. 0_rt)
setVal() [2/2]
mf_sustr setVal (windamp_u)
Variable Documentation
dstart
Real dstart =0.0_rt
Definition at line 5 of file REMORA_InitAnalyticSMFlux_ChannelTest.H.
mf_fcor
Real mf_fcor =1.0e-4_rt
Definition at line 7 of file REMORA_InitAnalyticSMFlux_ChannelTest.H.
Referenced by REMORA::advance_2d(), REMORA::init_beta_plane_coriolis(), and REMORA::setup_step().
tdays
Real tdays =time/Real(24.0*60.0*60.0)
Definition at line 4 of file REMORA_InitAnalyticSMFlux_ChannelTest.H.
time
Real time = remora.get_t_old(lev)
Definition at line 1 of file REMORA_InitAnalyticSMFlux_ChannelTest.H.
Referenced by REMORA::Advance(), REMORA::ErrorEst(), REMORAFillPatcher::Fill(), REMORA::fill_from_bdyfiles(), REMORA::FillCoarsePatch(), REMORA::FillCoarsePatchMap(), REMORA::FillCoarsePatchPC(), REMORA::FillPatch(), REMORA::FillPatchNoBC(), REMORAFillPatcher::FillRelax(), REMORAFillPatcher::FillSet(), REMORA::GetDataAtTime(), REMORA::init_only(), REMORA::is_it_time_for_action(), REMORA::MakeNewLevelFromCoarse(), REMORA::MakeNewLevelFromScratch(), REMORAPhysBCFunct::operator()(), REMORA::post_timestep(), REMORA::RemakeLevel(), REMORA::set_analytic_vmix(), REMORA::set_coriolis(), REMORA::set_hmixcoef(), TimeInterpolatedData::set_time(), REMORA::setup_step(), REMORA::sum_integrated_quantities(), REMORA::timeStep(), REMORA::timeStepML(), NCTimeSeriesBoundary::update_interpolated_to_time(), NCTimeSeriesRiver::update_interpolated_to_time(), NCTimeSeries::update_interpolated_to_time(), REMORA::WriteGenericPlotfileHeaderWithBathymetry(), REMORA::writeJobInfo(), and REMORA::WriteMultiLevelPlotfileWithBathymetry().
userval
Real userval =0.01_rt
Definition at line 6 of file REMORA_InitAnalyticSMFlux_ChannelTest.H.
windamp_u
Real windamp_u = userval*std::sin(0.9_rt*mf_fcor*86400.0_rt*(tdays-dstart))/m_solverChoice.rho0
Definition at line 12 of file REMORA_InitAnalyticSMFlux_ChannelTest.H.