REMORA: /home/runner/work/REMORA/REMORA/Source/Initialization/REMORA_init_from_netcdf.cpp File Reference
REMORA_init_from_netcdf.cpp File Reference
#include <REMORA.H>
#include <REMORA_Constants.H>
#include <REMORA_prob_common.H>
#include <REMORA_DataStruct.H>
Functions
void read_data_from_netcdf (int, const Box &domain, const std::string &fname, FArrayBox &NC_temp_fab, FArrayBox &NC_salt_fab, FArrayBox &NC_xvel_fab, FArrayBox &NC_yvel_fab)
helper function for reading in initial state data from netcdf
void read_data_full_domain_from_netcdf (int, const Box &domain, const std::string &fname, FArrayBox &NC_temp_fab, FArrayBox &NC_salt_fab, FArrayBox &NC_xvel_fab, FArrayBox &NC_yvel_fab, IntVect ngrow)
helper function for reading in full domain high-resolution initial state data from netcdf
void read_masks_from_netcdf (int, const Box &domain, const std::string &fname, FArrayBox &NC_mskr_fab, FArrayBox &NC_msku_fab, FArrayBox &NC_mskv_fab)
helper function for reading in land-sea masks from netcdf
Real read_bdry_from_netcdf (const Box &domain, const std::string &fname, Vector< Vector< FArrayBox > > &bdy_data_xlo, Vector< Vector< FArrayBox > > &bdy_data_xhi, Vector< Vector< FArrayBox > > &bdy_data_ylo, Vector< Vector< FArrayBox > > &bdy_data_yhi, int &width, amrex::Real &start_bdy_time, std::string bdry_time_varname, amrex::GpuArray< amrex::GpuArray< bool, AMREX_SPACEDIM *2 >, BdyVars::NumTypes+1 > &)
helper function for reading boundary data from netcdf
void init_state_from_netcdf (int lev, FArrayBox &temp_fab, FArrayBox &salt_fab, FArrayBox &x_vel_fab, FArrayBox &y_vel_fab, const Vector< FArrayBox > &NC_temp_fab, const Vector< FArrayBox > &NC_salt_fab, const Vector< FArrayBox > &NC_xvel_fab, const Vector< FArrayBox > &NC_yvel_fab)
helper function to initialize state from netcdf
void read_bathymetry_from_netcdf (int lev, const Box &domain, const std::string &fname, FArrayBox &NC_h_fab)
helper function to read bathymetry from netcdf
void read_grid_vars_from_netcdf (int lev, const Box &domain, const std::string &fname, FArrayBox &NC_pm_fab, FArrayBox &NC_pn_fab, FArrayBox &NC_xr_fab, FArrayBox &NC_yr_fab, FArrayBox &NC_xu_fab, FArrayBox &NC_yu_fab, FArrayBox &NC_xv_fab, FArrayBox &NC_yv_fab, FArrayBox &NC_xp_fab, FArrayBox &NC_yp_fab)
helper function to read grid variables from netcdf
void read_bathymetry_full_domain_from_netcdf (const Box &domain, const std::string &fname, FArrayBox &NC_h_fab, IntVect ngrow)
helper function to read full-domain high resolution bathymetry from netcdf
void read_grid_vars_full_domain_from_netcdf (const Box &domain, const std::string &fname, FArrayBox &NC_pm_fab, FArrayBox &NC_pn_fab, IntVect ngrow)
helper function to read full-domain high resolution grid variables from netcdf
void read_coriolis_from_netcdf (int lev, const Box &domain, const std::string &fname, FArrayBox &NC_fcor_fab)
helper function to read coriolis factor from netcdf
void read_zeta_from_netcdf (int lev, const Box &domain, const std::string &fname, FArrayBox &NC_zeta_fab)
helper function to read sea surface height from netcdf
void read_zeta_full_domain_from_netcdf (int lev, const Box &domain, const std::string &fname, FArrayBox &NC_zeta_fab, IntVect ngrow)
helper function to read high-resolution full-domain sea surface height from netcdf
void read_clim_nudg_coeff_from_netcdf (int lev, const Box &domain, const std::string &fname, bool do_m2_clim_nudg, bool do_m3_clim_nudg, bool do_temp_clim_nudg, bool do_salt_clim_nudg, FArrayBox &NC_M2NC_fab, FArrayBox &NC_M3NC_fab, FArrayBox &NC_TempNC_fab, FArrayBox &NC_SaltNC_fab)
helper function to read climatology nudging from netcdf
void read_vec_from_netcdf (int lev, const amrex::Vector< std::string > &fnames, const std::string &field_name, amrex::Vector< int > &vec_dat)
helper function to read in vector of data from netcdf
Function Documentation
init_state_from_netcdf()
void init_state_from_netcdf (int , FArrayBox & temp_fab, FArrayBox & salt_fab, FArrayBox & x_vel_fab, FArrayBox & y_vel_fab, const Vector< FArrayBox > & NC_temp_fab, const Vector< FArrayBox > & NC_salt_fab, const Vector< FArrayBox > & NC_xvel_fab, const Vector< FArrayBox > & NC_yvel_fab)
helper function to initialize state from netcdf
Helper function to initialize state and velocity data in a Fab.
Parameters
lev Integer specifying current level
state_fab FArrayBox object holding the state data we initialize
temp_fab FArrayBox object holding the temperature data we initialize
salt_fab FArrayBox object holding the salt data we initialize
x_vel_fab FArrayBox object holding the x-velocity data we initialize
y_vel_fab FArrayBox object holding the y-velocity data we initialize
NC_temp_fab Vector of FArrayBox objects with the REMORA dataset specifying temperature
NC_salt_fab Vector of FArrayBox objects with the REMORA dataset specifying salinity
NC_xvel_fab Vector of FArrayBox objects with the REMORA dataset specifying x-velocity
NC_yvel_fab Vector of FArrayBox objects with the REMORA dataset specifying y-velocity
Definition at line 576 of file REMORA_init_from_netcdf.cpp.
Referenced by REMORA::init_data_from_netcdf(), and REMORA::init_data_full_domain_from_netcdf().
read_bathymetry_from_netcdf()
void read_bathymetry_from_netcdf (int lev, const Box & domain, const std::string & fname, FArrayBox & NC_h_fab)
helper function to read bathymetry from netcdf
Parameters
lev level of data to read
domain simulation domain
fname file name to read from
NC_h_fab container for bathymetry data
Definition at line 129 of file REMORA_ReadFromInitNetcdf.cpp.
Referenced by REMORA::init_bathymetry_from_netcdf().
read_bathymetry_full_domain_from_netcdf()
void read_bathymetry_full_domain_from_netcdf (const Box & domain, const std::string & fname, FArrayBox & NC_h_fab, IntVect ngrow)
helper function to read full-domain high resolution bathymetry from netcdf
Parameters
domain simulation domain at nc_hires_grid_level
fname file name to read from
NC_h_fab container for bathymetry data
ngrow number of grow cells to read in, if not default
Definition at line 199 of file REMORA_ReadFromInitNetcdf.cpp.
Referenced by REMORA::init_bathymetry_full_domain_from_netcdf().
read_bdry_from_netcdf()
Real read_bdry_from_netcdf (const Box & domain, const std::string & fname, Vector< Vector< FArrayBox > > & bdy_data_xlo, Vector< Vector< FArrayBox > > & bdy_data_xhi, Vector< Vector< FArrayBox > > & bdy_data_ylo, Vector< Vector< FArrayBox > > & bdy_data_yhi, int & width, amrex::Real & start_bdy_time, std::string bdry_time_varname, amrex::GpuArray< amrex::GpuArray< bool, AMREX_SPACEDIM *2 >, BdyVars::NumTypes+1 > &)
helper function for reading boundary data from netcdf
read_clim_nudg_coeff_from_netcdf()
void read_clim_nudg_coeff_from_netcdf (int lev, const Box & domain, const std::string & fname, bool do_m2_clim_nudg, bool do_m3_clim_nudg, bool do_temp_clim_nudg, bool do_salt_clim_nudg, FArrayBox & NC_M2NC_fab, FArrayBox & NC_M3NC_fab, FArrayBox & NC_TempNC_fab, FArrayBox & NC_SaltNC_fab)
helper function to read climatology nudging from netcdf
Parameters
lev level of data to read
domain simulation domain
fname file name to read from
do_m2_clim_nudg whether to do 2d momentum climatology nudging
do_m3_clim_nudg whether to do 3d momentum climatology nudging
do_temp_clim_nudg whether to do temperature climatology nudging
do_salt_clim_nudg whether to do salinity climatology nudging
NC_M2NC_fab container for 2d momentum climatology data
NC_M3NC_fab container for 3d momentum climatology data
NC_TempNC_fab container for temperature climatology data
NC_SaltNC_fab container for salinity climatology data
Definition at line 309 of file REMORA_ReadFromInitNetcdf.cpp.
Referenced by REMORA::init_clim_nudg_coeff_from_netcdf().
read_coriolis_from_netcdf()
void read_coriolis_from_netcdf (int lev, const Box & domain, const std::string & fname, FArrayBox & NC_fcor_fab)
helper function to read coriolis factor from netcdf
Parameters
lev level of data to read
domain simulation domain
fname file name to read from
NC_fcor_fab container for Coriolis parameter data
Definition at line 248 of file REMORA_ReadFromInitNetcdf.cpp.
Referenced by REMORA::init_coriolis_from_netcdf().
read_data_from_netcdf()
void read_data_from_netcdf (int , const Box & domain, const std::string & fname, FArrayBox & NC_temp_fab, FArrayBox & NC_salt_fab, FArrayBox & NC_xvel_fab, FArrayBox & NC_yvel_fab)
helper function for reading in initial state data from netcdf
Parameters
lev level of data to read
domain simulation domain
fname file name to read from
NC_temp_fab container for temperature data
NC_salt_fab container for salinity data
NC_u_fab container for u velocity data
NC_v_fab container for v velocity data
Definition at line 18 of file REMORA_ReadFromInitNetcdf.cpp.
Referenced by REMORA::init_data_from_netcdf().
read_data_full_domain_from_netcdf()
void read_data_full_domain_from_netcdf (int , const Box & domain, const std::string & fname, FArrayBox & NC_temp_fab, FArrayBox & NC_salt_fab, FArrayBox & NC_xvel_fab, FArrayBox & NC_yvel_fab, IntVect ngrow)
helper function for reading in full domain high-resolution initial state data from netcdf
Parameters
lev level of data to read
domain simulation domain
fname file name to read from
NC_temp_fab container for temperature data
NC_salt_fab container for salinity data
NC_u_fab container for u velocity data
NC_v_fab container for v velocity data
ngrow number of grow cells to read
Definition at line 50 of file REMORA_ReadFromInitNetcdf.cpp.
Referenced by REMORA::init_data_full_domain_from_netcdf().
read_grid_vars_from_netcdf()
void read_grid_vars_from_netcdf (int lev, const Box & domain, const std::string & fname, FArrayBox & NC_pm_fab, FArrayBox & NC_pn_fab, FArrayBox & NC_xr_fab, FArrayBox & NC_yr_fab, FArrayBox & NC_xu_fab, FArrayBox & NC_yu_fab, FArrayBox & NC_xv_fab, FArrayBox & NC_yv_fab, FArrayBox & NC_xp_fab, FArrayBox & NC_yp_fab)
helper function to read grid variables from netcdf
Parameters
lev level of data to read
domain simulation domain
fname file name to read from
NC_pm_fab container for pm data
NC_pn_fab container for pn data
NC_xr_fab container for x_rho data
NC_yr_fab container for y_rho data
NC_xu_fab container for x_u data
NC_yu_fab container for y_u data
NC_xv_fab container for x_v data
NC_yv_fab container for y_v data
NC_xp_fab container for x_p data
NC_yp_fab container for y_p data
Definition at line 162 of file REMORA_ReadFromInitNetcdf.cpp.
Referenced by REMORA::init_grid_vars_from_netcdf().
read_grid_vars_full_domain_from_netcdf()
void read_grid_vars_full_domain_from_netcdf (const Box & domain, const std::string & fname, FArrayBox & NC_pm_fab, FArrayBox & NC_pn_fab, IntVect ngrow)
helper function to read full-domain high resolution grid variables from netcdf
Parameters
lev level of data to read
domain simulation domain
fname file name to read from
NC_pm_fab container for pm data
NC_pn_fab container for pn data
ngrow number of grow cells to read in, if not default
Definition at line 224 of file REMORA_ReadFromInitNetcdf.cpp.
Referenced by REMORA::init_grid_vars_full_domain_from_netcdf().
read_masks_from_netcdf()
void read_masks_from_netcdf (int , const Box & domain, const std::string & fname, FArrayBox & NC_mskr_fab, FArrayBox & NC_msku_fab, FArrayBox & NC_mskv_fab)
helper function for reading in land-sea masks from netcdf
Parameters
lev level of data to read
domain simulation domain
fname file name to read from
NC_mskr_fab container for rho-point land/sea mask data
NC_msku_fab container for u-point land/sea mask data
NC_mskv_fab container for v-point land/sea mask data
Definition at line 274 of file REMORA_ReadFromInitNetcdf.cpp.
Referenced by REMORA::init_masks_from_netcdf().
read_vec_from_netcdf()
void read_vec_from_netcdf (int lev, const amrex::Vector< std::string > & fnames, const std::string & field_name, amrex::Vector< int > & vec_dat)
helper function to read in vector of data from netcdf
Parameters
lev level of data to read
fnames file name(s) to read from
field_name field name to read
vec_dat vector to fill data
Definition at line 350 of file REMORA_ReadFromInitNetcdf.cpp.
Referenced by REMORA::init_riv_pos_from_netcdf().
read_zeta_from_netcdf()
void read_zeta_from_netcdf (int lev, const Box & domain, const std::string & fname, FArrayBox & NC_zeta_fab)
helper function to read sea surface height from netcdf
Parameters
lev level of data to read
domain simulation domain
fname file name to read from
NC_zeta_fab container for sea surface height data
Definition at line 79 of file REMORA_ReadFromInitNetcdf.cpp.
Referenced by REMORA::init_zeta_from_netcdf().
read_zeta_full_domain_from_netcdf()
void read_zeta_full_domain_from_netcdf (int lev, const Box & domain, const std::string & fname, FArrayBox & NC_zeta_fab, IntVect ngrow)
helper function to read high-resolution full-domain sea surface height from netcdf
Parameters
lev level of data to read
domain simulation domain
fname file name to read from
NC_zeta_fab container for sea surface height data
ngrow number of grow cells to read in, if not default
Definition at line 104 of file REMORA_ReadFromInitNetcdf.cpp.
Referenced by REMORA::init_zeta_full_domain_from_netcdf().