REMORA: /home/runner/work/REMORA/REMORA/Source/IO/REMORA_NCFile.H File Reference
REMORA_NCFile.H File Reference
#include <sstream>
#include <string>
#include <ctime>
#include <memory>
#include "AMReX_FArrayBox.H"
#include "AMReX_IArrayBox.H"
#include "REMORA_NCInterface.H"
Classes
struct NDArray< DataType >
NDArray is the datatype designed to hold any data, including scalars, multidimensional arrays, that read from the NetCDF file.
Typedefs
using PlaneVector = amrex::Vector< amrex::FArrayBox >
Enumerations
enum class NC_Data_Dims_Type {
Time_BT_SN_WE , Time_SN_WE , BT_SN_WE , SN_WE ,
Time_BT_Riv , Time_Riv , BT_Riv
}
Functions
template<typename DType >
void ReadNetCDFFile (const std::string &fname, amrex::Vector< std::string > names, amrex::Vector< NDArray< DType > > &arrays, bool one_time=false, int fill_time=0)
Read in data from netcdf file and save to data arrays.
std::string ReadNetCDFVarAttrStr (const std::string &fname, const std::string &var_name, const std::string &attr_name)
Helper function for reading a single variable attribute.
bool QueryNetCDFVarAttrStr (const std::string &fname, const std::string &var_name, const std::string &attr_name)
Helper function for testing for the presence of a single variable attribute.
template<class FAB , typename DType >
void fill_fab_from_arrays (int iv, amrex::Vector< NDArray< amrex::Real > > &nc_arrays, const std::string &var_name, NC_Data_Dims_Type &NC_dim_type, FAB &temp, amrex::IntVect custom_ngrow)
Helper function for reading data from NetCDF file into a provided FAB.
template<class FAB , typename DType >
void BuildFABsFromNetCDFFile (const amrex::Box &domain, const std::string &fname, amrex::Vector< std::string > nc_var_names, amrex::Vector< enum NC_Data_Dims_Type > NC_dim_types, amrex::Vector< FAB * > fab_vars, bool one_time=false, int fill_time=0, amrex::IntVect custom_ngrow=amrex::IntVect(1, 1, 0))
Function to read NetCDF variables and fill the corresponding Array4's.
Typedef Documentation
PlaneVector
using PlaneVector = amrex::Vector<amrex::FArrayBox>
Definition at line 14 of file REMORA_NCFile.H.
Enumeration Type Documentation
NC_Data_Dims_Type
enum class NC_Data_Dims_Type strong
Enumerator
Time_BT_SN_WE
Time_SN_WE
BT_SN_WE
SN_WE
Time_BT_Riv
Time_Riv
BT_Riv
Definition at line 16 of file REMORA_NCFile.H.
Function Documentation
BuildFABsFromNetCDFFile()
template<class FAB , typename DType > void BuildFABsFromNetCDFFile (const amrex::Box & domain, const std::string & fname, amrex::Vector< std::string > nc_var_names, amrex::Vector< enum NC_Data_Dims_Type > NC_dim_types, amrex::Vector< FAB * > fab_vars, bool one_time = false, int fill_time = 0, amrex::IntVect custom_ngrow = amrex::IntVect(1,1,0))
Function to read NetCDF variables and fill the corresponding Array4's.
Parameters
fname Name of the NetCDF file to be read
nc_var_names Variable names in the NetCDF file
NC_dim_types NetCDF data dimension types
fab_vars Fab data we are to fill
one_time Whether to read in a single time step from file
fill_time What time step to read from file, if only reading one step
custom_ngrow Number of grow cells to read in the fab; default is based off of one cell in each of x and y directions
Definition at line 298 of file REMORA_NCFile.H.
fill_fab_from_arrays()
template<class FAB , typename DType > void fill_fab_from_arrays (int iv, amrex::Vector< NDArray< amrex::Real > > & nc_arrays, const std::string & var_name, NC_Data_Dims_Type & NC_dim_type, FAB & temp, amrex::IntVect custom_ngrow)
Helper function for reading data from NetCDF file into a provided FAB.
Parameters
iv Index for which variable we are going to fill
nc_arrays Arrays of data from NetCDF file
var_name Variable name
NC_dim_type Dimension type for the variable as stored in the NetCDF file
temp FAB where we store the variable data from the NetCDF Arrays
custom_ngrow Custom number of grow cells for the FAB
Definition at line 178 of file REMORA_NCFile.H.
QueryNetCDFVarAttrStr()
bool QueryNetCDFVarAttrStr (const std::string & fname, const std::string & var_name, const std::string & attr_name)
Helper function for testing for the presence of a single variable attribute.
Parameters
fname Name of NetCDF file
var_name Name of variable
attr_name Name of attribute to read
Returns
whether attribute was found
Definition at line 40 of file REMORA_NCFile.cpp.
Referenced by NCTimeSeriesBoundary::Initialize().
ReadNetCDFFile()
template<typename DType > void ReadNetCDFFile (const std::string & fname, amrex::Vector< std::string > names, amrex::Vector< NDArray< DType > > & arrays, bool one_time = false, int fill_time = 0)
Read in data from netcdf file and save to data arrays.
Parameters
[in] fname file name to read from
[in] names field names to read
[in,out] arrays vector of data arrays to fill
[in] one_time whether to read in a single time step of data
[in] fill_time if reading a single time, what time step to read from the file?
Definition at line 91 of file REMORA_NCFile.H.
Referenced by BuildFABsFromNetCDFFile(), NCTimeSeries::Initialize(), NCTimeSeriesBoundary::Initialize(), NCTimeSeriesRiver::Initialize(), NCTimeSeriesBoundary::read_in_at_time(), and read_vec_from_netcdf().
ReadNetCDFVarAttrStr()
std::string ReadNetCDFVarAttrStr (const std::string & fname, const std::string & var_name, const std::string & attr_name)
Helper function for reading a single variable attribute.
Parameters
fname Name of NetCDF file
var_name Name of variable
attr_name Name of attribute to read
Returns
attribute value
Definition at line 13 of file REMORA_NCFile.cpp.
Referenced by NCTimeSeries::Initialize(), NCTimeSeriesBoundary::Initialize(), and NCTimeSeriesRiver::Initialize().