REMORA: /home/runner/work/REMORA/REMORA/Source/Prob/REMORA_InitAnalyticSMFlux_DoubleGyre.H File Reference
REMORA_InitAnalyticSMFlux_DoubleGyre.H File Reference
Functions
for (MFIter mfi((mf_sustr), TilingIfNotGPU());mfi.isValid();++mfi)
mf_svstr setVal (0.0_rt)
Variables
const auto prob_lo = geomdata.ProbLo()
const auto prob_hi = geomdata.ProbHi()
Real pi = 3.14159265359_rt
const Real yextent = prob_hi[1] - prob_lo[1]
const Real windamp = -0.05_rt / m_solverChoice.rho0
const Real val1 = 2.0_rt * pi / yextent
Function Documentation
for()
for (MFIter mfi((mf_sustr), TilingIfNotGPU());mfi.isValid();++ mfi)
Definition at line 10 of file REMORA_InitAnalyticSMFlux_DoubleGyre.H.
setVal()
mf_svstr setVal (0. 0_rt)
Variable Documentation
pi
Real pi = 3.14159265359_rt
Definition at line 5 of file REMORA_InitAnalyticSMFlux_DoubleGyre.H.
prob_hi
const auto prob_hi = geomdata.ProbHi()
Definition at line 2 of file REMORA_InitAnalyticSMFlux_DoubleGyre.H.
Referenced by add_par(), and for().
prob_lo
const auto prob_lo = geomdata.ProbLo()
Definition at line 1 of file REMORA_InitAnalyticSMFlux_DoubleGyre.H.
Referenced by add_par(), for(), for(), for(), and REMORA::init_beta_plane_coriolis().
val1
const Real val1 = 2.0_rt * pi / yextent
Definition at line 9 of file REMORA_InitAnalyticSMFlux_DoubleGyre.H.
Referenced by for().
windamp
const Real windamp = -0.05_rt / m_solverChoice.rho0
Definition at line 8 of file REMORA_InitAnalyticSMFlux_DoubleGyre.H.
Referenced by for().
yextent
const Real yextent = prob_hi[1] - prob_lo[1]
Definition at line 7 of file REMORA_InitAnalyticSMFlux_DoubleGyre.H.
Referenced by for().