REMORA: /home/runner/work/REMORA/REMORA/Source/IO/REMORA_Plotfile.cpp File Reference
REMORA_Plotfile.cpp File Reference
#include <REMORA.H>
#include "AMReX_Interp_3D_C.H"
#include "AMReX_PlotFileUtil.H"
Functions
template<typename V , typename T >
bool containerHasElement (const V &iterable, const T &query)
Variables
static PhysBCFunctNoOp null_bc_for_fill
Function Documentation
containerHasElement()
template<typename V , typename T > bool containerHasElement (const V & iterable, const T & query)
Definition at line 10 of file REMORA_Plotfile.cpp.
Referenced by REMORA::append2DPlotVariables(), REMORA::append3DPlotVariables(), REMORA::set2DPlotVariables(), REMORA::set3DPlotVariables(), and REMORA::WritePlotFile().
Variable Documentation
null_bc_for_fill
PhysBCFunctNoOp null_bc_for_fill static
Definition at line 7 of file REMORA_Plotfile.cpp.
Referenced by NCTimeSeries::update_interpolated_to_time(), and REMORA::WritePlotFile().