REMORA: /home/runner/work/REMORA/REMORA/Source/Prob/REMORA_InitAnalyticBathymetry_Upwelling_ML.H File Reference
REMORA_InitAnalyticBathymetry_Upwelling_ML.H File Reference
Functions
AMREX_ALWAYS_ASSERT (!m_solverChoice.flat_bathymetry)
mf_h setVal (geomdata.ProbHi(2))
if (lev==0 &&m_solverChoice.init_l1ad_T)
for (MFIter mfi(mf_h, TilingIfNotGPU());mfi.isValid();++mfi)
Variables
int rrx = remora.refRatio(0)[0]
int rry = remora.refRatio(0)[1]
else
const int Mm = geom.Domain().size()[1]
Function Documentation
AMREX_ALWAYS_ASSERT()
AMREX_ALWAYS_ASSERT (!m_solverChoice. flat_bathymetry)
for()
for (MFIter mfi(mf_h, TilingIfNotGPU());mfi.isValid();++ mfi)
Definition at line 63 of file REMORA_InitAnalyticBathymetry_Upwelling_ML.H.
if()
if (lev = =0 && m_solverChoice.init_l1ad_T)
Definition at line 11 of file REMORA_InitAnalyticBathymetry_Upwelling_ML.H.
setVal()
mf_h setVal (geomdata. ProbHi2)
Variable Documentation
else
else
Initial value:
{
        const int Lm = geom.Domain().size()[0]
Definition at line 60 of file REMORA_InitAnalyticBathymetry_Upwelling_ML.H.
Mm
const int Mm = geom.Domain().size()[1]
Definition at line 62 of file REMORA_InitAnalyticBathymetry_Upwelling_ML.H.
Referenced by for(), and if().
rrx
int rrx = remora.refRatio(0)[0]
Definition at line 2 of file REMORA_InitAnalyticBathymetry_Upwelling_ML.H.
Referenced by if(), REMORA::init_grid_vars_full_domain_from_netcdf(), and REMORA::set_grid_scale().
rry
int rry = remora.refRatio(0)[1]
Definition at line 3 of file REMORA_InitAnalyticBathymetry_Upwelling_ML.H.
Referenced by if(), REMORA::init_grid_vars_full_domain_from_netcdf(), and REMORA::set_grid_scale().