REMORA: /home/runner/work/REMORA/REMORA/Source/IO/REMORA_NCFile.cpp File Reference
REMORA_NCFile.cpp File Reference
#include <string>
#include "REMORA_NCFile.H"
#include "REMORA_NCInterface.H"
Functions
std::string ReadNetCDFVarAttrStr (const std::string &fname, const std::string &var_name, const std::string &attr_name)
Helper function for reading a single variable attribute.
Function Documentation
ReadNetCDFVarAttrStr()
std::string ReadNetCDFVarAttrStr (const std::string & fname, const std::string & var_name, const std::string & attr_name)
Helper function for reading a single variable attribute.
Parameters
fname Name of NetCDF file
var_name Name of variable
attr_name Name of attribute to read
Returns
attribute value
Definition at line 13 of file REMORA_NCFile.cpp.
Referenced by NCTimeSeries::Initialize(), NCTimeSeriesBoundary::Initialize(), and NCTimeSeriesRiver::Initialize().