REMORA: /home/runner/work/REMORA/REMORA/Source/Prob/REMORA_InitAnalyticBathymetry_BoundaryLayer.H File Reference
REMORA_InitAnalyticBathymetry_BoundaryLayer.H File Reference
Functions
AMREX_ALWAYS_ASSERT (!NSPeriodic||!EWPeriodic)
AMREX_ALWAYS_ASSERT (!m_solverChoice.flat_bathymetry)
mf_h setVal (geomdata.ProbHi(2))
for (MFIter mfi(mf_h, TilingIfNotGPU());mfi.isValid();++mfi)
Variables
const int Lm = geomdata.Domain().size()[0]
const int Mm = geomdata.Domain().size()[1]
Function Documentation
AMREX_ALWAYS_ASSERT() [1/2]
AMREX_ALWAYS_ASSERT (!m_solverChoice. flat_bathymetry)
AMREX_ALWAYS_ASSERT() [2/2]
AMREX_ALWAYS_ASSERT (!NSPeriodic||! EWPeriodic)
Referenced by REMORAFillPatcher::BuildMask(), REMORAFillPatcher::Define(), REMORAFillPatcher::Fill(), fill_fab_from_arrays(), REMORA::fill_from_bdyfiles(), for(), NCTimeSeries::get_interpolated_mf(), NCTimeSeriesBoundary::read_in_at_time(), read_vec_from_netcdf(), REMORA::refinement_criteria_setup(), REMORAFillPatcher::RegisterCoarseData(), derived::remora_dervort(), REMORAFillPatcher::REMORAFillPatcher(), and REMORA::WritePlotFile().
for()
for (MFIter mfi(mf_h, TilingIfNotGPU());mfi.isValid();++ mfi)
Definition at line 11 of file REMORA_InitAnalyticBathymetry_BoundaryLayer.H.
setVal()
mf_h setVal (geomdata. ProbHi2)
Variable Documentation
Lm
const int Lm = geomdata.Domain().size()[0]
Definition at line 8 of file REMORA_InitAnalyticBathymetry_BoundaryLayer.H.
Referenced by for(), and if().
Mm
const int Mm = geomdata.Domain().size()[1]
Definition at line 9 of file REMORA_InitAnalyticBathymetry_BoundaryLayer.H.