REMORA: /home/runner/work/REMORA/REMORA/Source/Prob/REMORA_InitAnalyticGridScale_BoundaryLayer.H File Reference
REMORA_InitAnalyticGridScale_BoundaryLayer.H File Reference
Functions
for (MFIter mfi(mf_pm, TilingIfNotGPU());mfi.isValid();++mfi)
mf_pn setVal (dxi[1])
Variables
auto geomdata = geom.data()
const int Lm = geomdata.Domain().size()[0]
const auto dxi = geom.InvCellSize()
Function Documentation
for()
for (MFIter mfi(mf_pm, TilingIfNotGPU());mfi.isValid();++ mfi)
Definition at line 5 of file REMORA_InitAnalyticGridScale_BoundaryLayer.H.
setVal()
mf_pn setVal (dxi [1])
Variable Documentation
dxi
const auto dxi = geom.InvCellSize()
Definition at line 4 of file REMORA_InitAnalyticGridScale_BoundaryLayer.H.
Referenced by REMORA::set_grid_scale().
geomdata
auto geomdata = geom.data()
Definition at line 2 of file REMORA_InitAnalyticGridScale_BoundaryLayer.H.
Referenced by for(), for(), REMORA::gls_corrector(), REMORA::gls_prestep(), if(), REMORAPhysBCFunct::impose_cons_bcs(), REMORAPhysBCFunct::impose_xvel_bcs(), REMORAPhysBCFunct::impose_yvel_bcs(), REMORAPhysBCFunct::impose_zvel_bcs(), REMORA::init_beta_plane_coriolis(), REMORA::prestep_t_advection(), REMORA::rhs_t_3d(), REMORA::rhs_uv_2d(), REMORA::rhs_uv_3d(), REMORA::stretch_transform(), and REMORA::update_massflux_3d().
Lm
const int Lm = geomdata.Domain().size()[0]
Definition at line 3 of file REMORA_InitAnalyticGridScale_BoundaryLayer.H.
Referenced by for().