REMORA: TimeInterpolatedData Struct Reference
TimeInterpolatedData Struct Reference
#include <REMORA_TimeInterpolatedData.H>
Public Member Functions
TimeInterpolatedData ()
TimeInterpolatedData (amrex::Real time)
~TimeInterpolatedData ()
void set_time (amrex::Real time)
amrex::Real get_time ()
void add_var (amrex::MultiFab *var_data, int own_data)
amrex::MultiFab & get_var (int var_idx)
int num_vars ()
void clear ()
Public Attributes
const int owning = 1
const int non_owning = 0
Private Attributes
amrex::Vector< amrex::MultiFab * > m_data
amrex::Vector< int > m_owns_data
amrex::Real m_time
Detailed Description
Definition at line 8 of file REMORA_TimeInterpolatedData.H.
Constructor & Destructor Documentation
TimeInterpolatedData() [1/2]
TimeInterpolatedData::TimeInterpolatedData () inline
Definition at line 9 of file REMORA_TimeInterpolatedData.H.
TimeInterpolatedData() [2/2]
TimeInterpolatedData::TimeInterpolatedData (amrex::Real time) inline
Definition at line 11 of file REMORA_TimeInterpolatedData.H.
~TimeInterpolatedData()
TimeInterpolatedData::~TimeInterpolatedData () inline
Definition at line 13 of file REMORA_TimeInterpolatedData.H.
Member Function Documentation
add_var()
void TimeInterpolatedData::add_var (amrex::MultiFab * var_data, int own_data) inline
Definition at line 23 of file REMORA_TimeInterpolatedData.H.
Referenced by REMORA::GetDataAtTime().
clear()
void TimeInterpolatedData::clear () inline
Definition at line 34 of file REMORA_TimeInterpolatedData.H.
Referenced by ~TimeInterpolatedData().
get_time()
amrex::Real TimeInterpolatedData::get_time () inline
Definition at line 21 of file REMORA_TimeInterpolatedData.H.
Referenced by REMORA::FillCoarsePatchMap().
get_var()
amrex::MultiFab & TimeInterpolatedData::get_var (int var_idx) inline
Definition at line 28 of file REMORA_TimeInterpolatedData.H.
Referenced by REMORA::GetDataAtTime().
num_vars()
int TimeInterpolatedData::num_vars () inline
Definition at line 32 of file REMORA_TimeInterpolatedData.H.
Referenced by clear().
set_time()
void TimeInterpolatedData::set_time (amrex::Real time) inline
Definition at line 17 of file REMORA_TimeInterpolatedData.H.
Referenced by REMORA::GetDataAtTime().
Member Data Documentation
m_data
amrex::Vector<amrex::MultiFab*> TimeInterpolatedData::m_data private
Definition at line 53 of file REMORA_TimeInterpolatedData.H.
Referenced by add_var(), clear(), get_var(), and num_vars().
m_owns_data
amrex::Vector<int> TimeInterpolatedData::m_owns_data private
Definition at line 54 of file REMORA_TimeInterpolatedData.H.
Referenced by add_var(), and clear().
m_time
amrex::Real TimeInterpolatedData::m_time private
Definition at line 55 of file REMORA_TimeInterpolatedData.H.
Referenced by clear(), get_time(), and set_time().
non_owning
const int TimeInterpolatedData::non_owning = 0
Definition at line 50 of file REMORA_TimeInterpolatedData.H.
Referenced by REMORA::GetDataAtTime().
owning
const int TimeInterpolatedData::owning = 1
Definition at line 49 of file REMORA_TimeInterpolatedData.H.
Referenced by clear(), and REMORA::GetDataAtTime().
The documentation for this struct was generated from the following file:
/home/runner/work/REMORA/REMORA/Source/BoundaryConditions/REMORA_TimeInterpolatedData.H