REMORA: SolverChoice Struct Reference
SolverChoice Struct Reference
#include <REMORA_DataStruct.H>
Public Member Functions
void init_params ()
read in and initialize parameters
void display ()
Public Attributes
std::string pp_prefix {"remora"}
bool flat_bathymetry = false
bool use_salt = true
bool use_coriolis = false
bool use_prestep = true
bool use_uv3dmix = true
bool use_baroclinic = true
bool use_barotropic = true
bool bulk_fluxes = false
bool do_temp_flux = false
bool do_salt_flux = false
bool do_rivers = false
bool do_rivers_temp = true
bool do_rivers_salt = true
bool do_rivers_scalar = false
amrex::Vector< int > do_rivers_cons
bool init_l1ad_h = false
bool init_l1ad_T = false
bool init_ana_h = false
bool init_ana_T = false
bool init_l0int_h = true
bool init_l0int_T = true
AdvectionScheme tracer_Hadv_scheme
AdvectionScheme uv_Hadv_scheme
CouplingType coupling_type
IC_Type ic_type
Cor_Type coriolis_type
SMFluxType smflux_type
WindType wind_type
EOSType eos_type
BottomStressType bottom_stress_type
MaskType mask_type
VertMixingType vert_mixing_type
HorizMixingType horiz_mixing_type
GLS_StabilityType gls_stability_type
GridScaleType grid_scale_type
amrex::Real theta_s = amrex::Real(3.0)
amrex::Real theta_b = amrex::Real(0.0)
amrex::Real tcline = amrex::Real(150.0)
amrex::Real rdrag = amrex::Real(3e-4)
amrex::Real rdrag2 = amrex::Real(3e-3)
amrex::Real Zob = amrex::Real(2e-2)
amrex::Real Zos = amrex::Real(2e-2)
amrex::Real Cdb_max = amrex::Real(0.5)
amrex::Real Cdb_min = amrex::Real(1e-6)
amrex::Real R0 = amrex::Real(1028)
amrex::Real S0 = amrex::Real(35.0)
amrex::Real T0 = amrex::Real(5.0)
amrex::Real Tcoef = amrex::Real(1.7e-4)
amrex::Real Scoef = amrex::Real(0.0)
amrex::Real rho0 = amrex::Real(1025.0)
amrex::Real coriolis_f0 = amrex::Real(0.0)
amrex::Real coriolis_beta = amrex::Real(0.0)
amrex::Real Pair = amrex::Real(1013.48)
amrex::Real Tair = amrex::Real(23.567)
amrex::Real Hair = amrex::Real(0.776)
amrex::Real cloud = amrex::Real(0.0)
amrex::Real rain = amrex::Real(0.0)
amrex::Real blk_ZQ = amrex::Real(10.0)
amrex::Real blk_ZT = amrex::Real(10.0)
amrex::Real blk_ZW = amrex::Real(10.0)
bool eminusp = false
bool eminusp_correct_ssh = false
amrex::Real srflux = amrex::Real(0.0)
int spatial_order = 2
amrex::Real visc2 = amrex::Real(0.0)
amrex::Vector< amrex::Real > tnu2
amrex::Real gls_p = amrex::Real(3.0)
amrex::Real gls_m = amrex::Real(1.5)
amrex::Real gls_n = amrex::Real(-1.0)
amrex::Real gls_Kmin = amrex::Real(7.6e-6)
amrex::Real gls_Pmin = amrex::Real(1.0e-12)
amrex::Real gls_cmu0 = amrex::Real(0.5477)
amrex::Real gls_c1 = amrex::Real(1.44)
amrex::Real gls_c2 = amrex::Real(1.92)
amrex::Real gls_c3m = amrex::Real(-0.4)
amrex::Real gls_c3p = amrex::Real(1.0)
amrex::Real gls_sigk = amrex::Real(1.0)
amrex::Real gls_sigp = amrex::Real(1.3)
amrex::Real Akk_bak = amrex::Real(5.0e-6)
amrex::Real Akp_bak = amrex::Real(5.0e-6)
amrex::Real Akv_bak = amrex::Real(5.0e-6)
amrex::Real Akt_bak = amrex::Real(1.0e-6)
amrex::Real gls_Gh0
amrex::Real gls_Ghcri
amrex::Real gls_Ghmin = amrex::Real(-0.28)
amrex::Real gls_E2 = amrex::Real(1.33)
amrex::Real gls_L1
amrex::Real gls_L2
amrex::Real gls_L3
amrex::Real gls_L4
amrex::Real gls_L5
amrex::Real gls_L6
amrex::Real gls_L7
amrex::Real gls_L8
amrex::Real my_A1 = amrex::Real(0.92)
amrex::Real my_A2 = amrex::Real(0.74)
amrex::Real my_B1 = amrex::Real(16.6)
amrex::Real my_B2 = amrex::Real(10.1)
amrex::Real my_C1 = amrex::Real(0.08)
amrex::Real my_C2 = amrex::Real(0.7)
amrex::Real my_C3 = amrex::Real(0.2)
amrex::Real my_E1 = amrex::Real(1.8)
amrex::Real my_E2 = amrex::Real(1.33)
amrex::Real my_Gh0 = amrex::Real(0.0233)
amrex::Real my_Sq = amrex::Real(0.2)
amrex::Real my_dtfac = amrex::Real(0.05)
amrex::Real my_lmax = amrex::Real(0.53)
amrex::Real my_qmin = amrex::Real(1.0E-8)
amrex::Vector< amrex::Real > nudg_coeff
amrex::Real obcfac = amrex::Real(0.0)
bool do_m2_clim_nudg = false
bool do_m3_clim_nudg = false
bool do_temp_clim_nudg = false
bool do_salt_clim_nudg = false
bool do_any_clim_nudg = false
bool boundary_from_netcdf = false
Detailed Description
Definition at line 89 of file REMORA_DataStruct.H.
Member Function Documentation
display()
void SolverChoice::display () inline
Definition at line 481 of file REMORA_DataStruct.H.
init_params()
void SolverChoice::init_params () inline
read in and initialize parameters
Definition at line 92 of file REMORA_DataStruct.H.
Referenced by REMORA::ReadParameters().
Member Data Documentation
Akk_bak
amrex::Real SolverChoice::Akk_bak = amrex::Real(5.0e-6)
Definition at line 679 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector(), REMORA::init_gls_vmix(), init_params(), and REMORA::init_stuff().
Akp_bak
amrex::Real SolverChoice::Akp_bak = amrex::Real(5.0e-6)
Definition at line 680 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector(), REMORA::init_gls_vmix(), init_params(), and REMORA::init_stuff().
Akt_bak
amrex::Real SolverChoice::Akt_bak = amrex::Real(1.0e-6)
Definition at line 682 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector(), REMORA::init_gls_vmix(), and init_params().
Akv_bak
amrex::Real SolverChoice::Akv_bak = amrex::Real(5.0e-6)
Definition at line 681 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector(), REMORA::init_gls_vmix(), and init_params().
blk_ZQ
amrex::Real SolverChoice::blk_ZQ = amrex::Real(10.0)
Definition at line 646 of file REMORA_DataStruct.H.
Referenced by REMORA::bulk_fluxes(), and init_params().
blk_ZT
amrex::Real SolverChoice::blk_ZT = amrex::Real(10.0)
Definition at line 647 of file REMORA_DataStruct.H.
Referenced by REMORA::bulk_fluxes(), and init_params().
blk_ZW
amrex::Real SolverChoice::blk_ZW = amrex::Real(10.0)
Definition at line 648 of file REMORA_DataStruct.H.
Referenced by REMORA::bulk_fluxes(), and init_params().
bottom_stress_type
BottomStressType SolverChoice::bottom_stress_type
Definition at line 593 of file REMORA_DataStruct.H.
Referenced by init_params(), REMORA::init_stuff(), REMORA::ReadCheckpointFile(), REMORA::setup_step(), and REMORA::WriteCheckpointFile().
boundary_from_netcdf
bool SolverChoice::boundary_from_netcdf = false
Definition at line 729 of file REMORA_DataStruct.H.
Referenced by REMORA::advance_3d(), REMORA::FillCoarsePatchMap(), REMORA::FillPatch(), REMORA::init_bcs(), REMORA::init_only(), and REMORA::init_zeta_from_netcdf().
bulk_fluxes
bool SolverChoice::bulk_fluxes = false
Definition at line 552 of file REMORA_DataStruct.H.
Referenced by init_params(), REMORA::init_stuff(), REMORA::nonlin_eos(), and REMORA::setup_step().
Cdb_max
amrex::Real SolverChoice::Cdb_max = amrex::Real(0.5)
Definition at line 620 of file REMORA_DataStruct.H.
Referenced by init_params(), and REMORA::setup_step().
Cdb_min
amrex::Real SolverChoice::Cdb_min = amrex::Real(1e-6)
Definition at line 621 of file REMORA_DataStruct.H.
Referenced by init_params(), and REMORA::setup_step().
cloud
amrex::Real SolverChoice::cloud = amrex::Real(0.0)
Definition at line 642 of file REMORA_DataStruct.H.
Referenced by REMORA::bulk_fluxes(), and init_params().
coriolis_beta
amrex::Real SolverChoice::coriolis_beta = amrex::Real(0.0)
Definition at line 633 of file REMORA_DataStruct.H.
Referenced by REMORA::init_beta_plane_coriolis(), and init_params().
coriolis_f0
amrex::Real SolverChoice::coriolis_f0 = amrex::Real(0.0)
Definition at line 632 of file REMORA_DataStruct.H.
Referenced by REMORA::init_beta_plane_coriolis(), and init_params().
coriolis_type
Cor_Type SolverChoice::coriolis_type
Definition at line 581 of file REMORA_DataStruct.H.
Referenced by display(), init_params(), and REMORA::set_coriolis().
coupling_type
CouplingType SolverChoice::coupling_type
Definition at line 575 of file REMORA_DataStruct.H.
Referenced by display(), init_params(), REMORA::InitData(), REMORA::post_timestep(), REMORA::timeStep(), and REMORA::timeStepML().
do_any_clim_nudg
bool SolverChoice::do_any_clim_nudg = false
Definition at line 727 of file REMORA_DataStruct.H.
Referenced by REMORA::init_clim_nudg_coeff(), REMORA::init_only(), and init_params().
do_m2_clim_nudg
bool SolverChoice::do_m2_clim_nudg = false
Definition at line 723 of file REMORA_DataStruct.H.
Referenced by REMORA::advance_2d(), REMORA::init_clim_nudg_coeff_from_netcdf(), REMORA::init_only(), and init_params().
do_m3_clim_nudg
bool SolverChoice::do_m3_clim_nudg = false
Definition at line 724 of file REMORA_DataStruct.H.
Referenced by REMORA::init_clim_nudg_coeff_from_netcdf(), REMORA::init_only(), init_params(), and REMORA::setup_step().
do_rivers
bool SolverChoice::do_rivers = false
Definition at line 556 of file REMORA_DataStruct.H.
Referenced by REMORA::advance_2d(), REMORA::advance_3d(), REMORA::init_only(), init_params(), REMORA::init_stuff(), REMORA::prestep(), REMORA::prestep_t_advection(), and REMORA::rhs_t_3d().
do_rivers_cons
amrex::Vector<int> SolverChoice::do_rivers_cons
Definition at line 560 of file REMORA_DataStruct.H.
Referenced by REMORA::advance_3d(), REMORA::init_only(), init_params(), and REMORA::prestep().
do_rivers_salt
bool SolverChoice::do_rivers_salt = true
Definition at line 558 of file REMORA_DataStruct.H.
Referenced by init_params().
do_rivers_scalar
bool SolverChoice::do_rivers_scalar = false
Definition at line 559 of file REMORA_DataStruct.H.
Referenced by init_params().
do_rivers_temp
bool SolverChoice::do_rivers_temp = true
Definition at line 557 of file REMORA_DataStruct.H.
Referenced by init_params().
do_salt_clim_nudg
bool SolverChoice::do_salt_clim_nudg = false
Definition at line 726 of file REMORA_DataStruct.H.
Referenced by REMORA::advance_3d(), REMORA::init_clim_nudg_coeff_from_netcdf(), REMORA::init_only(), and init_params().
do_salt_flux
bool SolverChoice::do_salt_flux = false
Definition at line 554 of file REMORA_DataStruct.H.
Referenced by init_params(), and REMORA::setup_step().
do_temp_clim_nudg
bool SolverChoice::do_temp_clim_nudg = false
Definition at line 725 of file REMORA_DataStruct.H.
Referenced by REMORA::advance_3d(), REMORA::init_clim_nudg_coeff_from_netcdf(), REMORA::init_only(), and init_params().
do_temp_flux
bool SolverChoice::do_temp_flux = false
Definition at line 553 of file REMORA_DataStruct.H.
Referenced by init_params(), and REMORA::setup_step().
eminusp
bool SolverChoice::eminusp = false
Definition at line 650 of file REMORA_DataStruct.H.
Referenced by init_params().
eminusp_correct_ssh
bool SolverChoice::eminusp_correct_ssh = false
Definition at line 651 of file REMORA_DataStruct.H.
Referenced by init_params(), and REMORA::set_zeta_to_Ztavg().
eos_type
EOSType SolverChoice::eos_type
Definition at line 590 of file REMORA_DataStruct.H.
Referenced by init_params(), and REMORA::rho_eos().
flat_bathymetry
bool SolverChoice::flat_bathymetry = false
Definition at line 539 of file REMORA_DataStruct.H.
Referenced by display(), init_params(), REMORA::prestep_t_advection(), REMORA::rhs_t_3d(), and REMORA::set_bathymetry().
gls_c1
amrex::Real SolverChoice::gls_c1 = amrex::Real(1.44)
Definition at line 671 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector(), and init_params().
gls_c2
amrex::Real SolverChoice::gls_c2 = amrex::Real(1.92)
Definition at line 672 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector(), and init_params().
gls_c3m
amrex::Real SolverChoice::gls_c3m = amrex::Real(-0.4)
Definition at line 673 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector(), and init_params().
gls_c3p
amrex::Real SolverChoice::gls_c3p = amrex::Real(1.0)
Definition at line 674 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector(), and init_params().
gls_cmu0
amrex::Real SolverChoice::gls_cmu0 = amrex::Real(0.5477)
Definition at line 670 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector(), and init_params().
gls_E2
amrex::Real SolverChoice::gls_E2 = amrex::Real(1.33)
Definition at line 688 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector().
gls_Gh0
amrex::Real SolverChoice::gls_Gh0
Definition at line 685 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector(), and init_params().
gls_Ghcri
amrex::Real SolverChoice::gls_Ghcri
Definition at line 686 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector(), and init_params().
gls_Ghmin
amrex::Real SolverChoice::gls_Ghmin = amrex::Real(-0.28)
Definition at line 687 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector().
gls_Kmin
amrex::Real SolverChoice::gls_Kmin = amrex::Real(7.6e-6)
Definition at line 667 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector(), REMORA::init_gls_vmix(), init_params(), and REMORA::init_stuff().
gls_L1
amrex::Real SolverChoice::gls_L1
Definition at line 690 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector(), and init_params().
gls_L2
amrex::Real SolverChoice::gls_L2
Definition at line 691 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector(), and init_params().
gls_L3
amrex::Real SolverChoice::gls_L3
Definition at line 692 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector(), and init_params().
gls_L4
amrex::Real SolverChoice::gls_L4
Definition at line 693 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector(), and init_params().
gls_L5
amrex::Real SolverChoice::gls_L5
Definition at line 694 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector(), and init_params().
gls_L6
amrex::Real SolverChoice::gls_L6
Definition at line 695 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector(), and init_params().
gls_L7
amrex::Real SolverChoice::gls_L7
Definition at line 696 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector(), and init_params().
gls_L8
amrex::Real SolverChoice::gls_L8
Definition at line 697 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector(), and init_params().
gls_m
amrex::Real SolverChoice::gls_m = amrex::Real(1.5)
Definition at line 665 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector(), and init_params().
gls_n
amrex::Real SolverChoice::gls_n = amrex::Real(-1.0)
Definition at line 666 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector(), and init_params().
gls_p
amrex::Real SolverChoice::gls_p = amrex::Real(3.0)
Definition at line 664 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector(), and init_params().
gls_Pmin
amrex::Real SolverChoice::gls_Pmin = amrex::Real(1.0e-12)
Definition at line 668 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector(), REMORA::init_gls_vmix(), init_params(), and REMORA::init_stuff().
gls_sigk
amrex::Real SolverChoice::gls_sigk = amrex::Real(1.0)
Definition at line 675 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector(), and init_params().
gls_sigp
amrex::Real SolverChoice::gls_sigp = amrex::Real(1.3)
Definition at line 676 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector(), and init_params().
gls_stability_type
GLS_StabilityType SolverChoice::gls_stability_type
Definition at line 601 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector(), and init_params().
grid_scale_type
GridScaleType SolverChoice::grid_scale_type
Definition at line 604 of file REMORA_DataStruct.H.
Referenced by init_params(), and REMORA::set_grid_scale().
Hair
amrex::Real SolverChoice::Hair = amrex::Real(0.776)
Definition at line 640 of file REMORA_DataStruct.H.
Referenced by REMORA::bulk_fluxes(), and init_params().
horiz_mixing_type
HorizMixingType SolverChoice::horiz_mixing_type
Definition at line 600 of file REMORA_DataStruct.H.
Referenced by init_params(), and REMORA::set_hmixcoef().
ic_type
IC_Type SolverChoice::ic_type
Definition at line 578 of file REMORA_DataStruct.H.
Referenced by display(), REMORA::init_only(), init_params(), REMORA::set_bathymetry(), REMORA::set_grid_scale(), and REMORA::set_zeta().
init_ana_h
bool SolverChoice::init_ana_h = false
Definition at line 565 of file REMORA_DataStruct.H.
Referenced by init_params(), and REMORA::set_bathymetry().
init_ana_T
bool SolverChoice::init_ana_T = false
Definition at line 566 of file REMORA_DataStruct.H.
Referenced by REMORA::init_only(), and init_params().
init_l0int_h
bool SolverChoice::init_l0int_h = true
Definition at line 568 of file REMORA_DataStruct.H.
Referenced by init_params(), and REMORA::set_bathymetry().
init_l0int_T
bool SolverChoice::init_l0int_T = true
Definition at line 569 of file REMORA_DataStruct.H.
Referenced by REMORA::init_only(), and init_params().
init_l1ad_h
bool SolverChoice::init_l1ad_h = false
Definition at line 562 of file REMORA_DataStruct.H.
Referenced by init_params(), and REMORA::set_bathymetry().
init_l1ad_T
bool SolverChoice::init_l1ad_T = false
Definition at line 563 of file REMORA_DataStruct.H.
Referenced by REMORA::init_only(), init_params(), and REMORA::timeStepML().
mask_type
MaskType SolverChoice::mask_type
Definition at line 596 of file REMORA_DataStruct.H.
Referenced by init_params(), and REMORA::set_masks().
my_A1
amrex::Real SolverChoice::my_A1 = amrex::Real(0.92)
Definition at line 700 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector().
my_A2
amrex::Real SolverChoice::my_A2 = amrex::Real(0.74)
Definition at line 701 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector().
my_B1
amrex::Real SolverChoice::my_B1 = amrex::Real(16.6)
Definition at line 702 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector().
my_B2
amrex::Real SolverChoice::my_B2 = amrex::Real(10.1)
Definition at line 703 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector().
my_C1
amrex::Real SolverChoice::my_C1 = amrex::Real(0.08)
Definition at line 704 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector().
my_C2
amrex::Real SolverChoice::my_C2 = amrex::Real(0.7)
Definition at line 705 of file REMORA_DataStruct.H.
my_C3
amrex::Real SolverChoice::my_C3 = amrex::Real(0.2)
Definition at line 706 of file REMORA_DataStruct.H.
my_dtfac
amrex::Real SolverChoice::my_dtfac = amrex::Real(0.05)
Definition at line 711 of file REMORA_DataStruct.H.
my_E1
amrex::Real SolverChoice::my_E1 = amrex::Real(1.8)
Definition at line 707 of file REMORA_DataStruct.H.
my_E2
amrex::Real SolverChoice::my_E2 = amrex::Real(1.33)
Definition at line 708 of file REMORA_DataStruct.H.
my_Gh0
amrex::Real SolverChoice::my_Gh0 = amrex::Real(0.0233)
Definition at line 709 of file REMORA_DataStruct.H.
my_lmax
amrex::Real SolverChoice::my_lmax = amrex::Real(0.53)
Definition at line 712 of file REMORA_DataStruct.H.
my_qmin
amrex::Real SolverChoice::my_qmin = amrex::Real(1.0E-8)
Definition at line 713 of file REMORA_DataStruct.H.
my_Sq
amrex::Real SolverChoice::my_Sq = amrex::Real(0.2)
Definition at line 710 of file REMORA_DataStruct.H.
nudg_coeff
amrex::Vector<amrex::Real> SolverChoice::nudg_coeff
Definition at line 716 of file REMORA_DataStruct.H.
Referenced by REMORA::init_clim_nudg_coeff(), and init_params().
obcfac
amrex::Real SolverChoice::obcfac = amrex::Real(0.0)
Definition at line 720 of file REMORA_DataStruct.H.
Referenced by REMORA::fill_from_bdyfiles(), and init_params().
Pair
amrex::Real SolverChoice::Pair = amrex::Real(1013.48)
Definition at line 636 of file REMORA_DataStruct.H.
Referenced by REMORA::bulk_fluxes(), and init_params().
pp_prefix
std::string SolverChoice::pp_prefix {"remora"}
Definition at line 537 of file REMORA_DataStruct.H.
Referenced by init_params().
R0
amrex::Real SolverChoice::R0 = amrex::Real(1028)
Definition at line 624 of file REMORA_DataStruct.H.
Referenced by init_params(), and REMORA::lin_eos().
rain
amrex::Real SolverChoice::rain = amrex::Real(0.0)
Definition at line 644 of file REMORA_DataStruct.H.
Referenced by init_params(), and REMORA::init_stuff().
rdrag
amrex::Real SolverChoice::rdrag = amrex::Real(3e-4)
Definition at line 612 of file REMORA_DataStruct.H.
Referenced by init_params(), and REMORA::init_stuff().
rdrag2
amrex::Real SolverChoice::rdrag2 = amrex::Real(3e-3)
Definition at line 614 of file REMORA_DataStruct.H.
Referenced by init_params(), and REMORA::init_stuff().
rho0
amrex::Real SolverChoice::rho0 = amrex::Real(1025.0)
Definition at line 629 of file REMORA_DataStruct.H.
Referenced by REMORA::bulk_fluxes(), init_params(), REMORA::lin_eos(), REMORA::nonlin_eos(), and REMORA::prsgrd().
S0
amrex::Real SolverChoice::S0 = amrex::Real(35.0)
Definition at line 625 of file REMORA_DataStruct.H.
Referenced by init_params(), and REMORA::lin_eos().
Scoef
amrex::Real SolverChoice::Scoef = amrex::Real(0.0)
Definition at line 628 of file REMORA_DataStruct.H.
Referenced by init_params(), and REMORA::lin_eos().
smflux_type
SMFluxType SolverChoice::smflux_type
Definition at line 584 of file REMORA_DataStruct.H.
Referenced by REMORA::init_only(), init_params(), and REMORA::set_smflux().
spatial_order
int SolverChoice::spatial_order = 2
Definition at line 657 of file REMORA_DataStruct.H.
Referenced by display(), REMORA::MakeNewLevelFromScratch(), and REMORA::RemakeLevel().
srflux
amrex::Real SolverChoice::srflux = amrex::Real(0.0)
Definition at line 654 of file REMORA_DataStruct.H.
Referenced by REMORA::bulk_fluxes(), and init_params().
T0
amrex::Real SolverChoice::T0 = amrex::Real(5.0)
Definition at line 626 of file REMORA_DataStruct.H.
Referenced by init_params(), and REMORA::lin_eos().
Tair
amrex::Real SolverChoice::Tair = amrex::Real(23.567)
Definition at line 638 of file REMORA_DataStruct.H.
Referenced by REMORA::bulk_fluxes(), and init_params().
tcline
amrex::Real SolverChoice::tcline = amrex::Real(150.0)
Definition at line 609 of file REMORA_DataStruct.H.
Referenced by init_params(), REMORA::stretch_transform(), and REMORA::WriteNCPlotFile_which().
Tcoef
amrex::Real SolverChoice::Tcoef = amrex::Real(1.7e-4)
Definition at line 627 of file REMORA_DataStruct.H.
Referenced by init_params(), and REMORA::lin_eos().
theta_b
amrex::Real SolverChoice::theta_b = amrex::Real(0.0)
Definition at line 608 of file REMORA_DataStruct.H.
Referenced by REMORA::calc_stretch_coeffs(), init_params(), and REMORA::WriteNCPlotFile_which().
theta_s
amrex::Real SolverChoice::theta_s = amrex::Real(3.0)
Definition at line 607 of file REMORA_DataStruct.H.
Referenced by REMORA::calc_stretch_coeffs(), init_params(), and REMORA::WriteNCPlotFile_which().
tnu2
amrex::Vector<amrex::Real> SolverChoice::tnu2
Definition at line 661 of file REMORA_DataStruct.H.
Referenced by init_params(), and REMORA::set_hmixcoef().
tracer_Hadv_scheme
AdvectionScheme SolverChoice::tracer_Hadv_scheme
Definition at line 571 of file REMORA_DataStruct.H.
Referenced by display(), init_params(), REMORA::prestep_t_advection(), and REMORA::rhs_t_3d().
use_baroclinic
bool SolverChoice::use_baroclinic = true
Definition at line 549 of file REMORA_DataStruct.H.
use_barotropic
bool SolverChoice::use_barotropic = true
Definition at line 550 of file REMORA_DataStruct.H.
Referenced by REMORA::Advance(), display(), init_params(), and REMORA::timeStepML().
use_coriolis
bool SolverChoice::use_coriolis = false
Definition at line 544 of file REMORA_DataStruct.H.
Referenced by REMORA::advance_2d(), display(), init_params(), REMORA::set_coriolis(), and REMORA::setup_step().
use_prestep
bool SolverChoice::use_prestep = true
Definition at line 547 of file REMORA_DataStruct.H.
Referenced by display(), init_params(), and REMORA::setup_step().
use_salt
bool SolverChoice::use_salt = true
Definition at line 541 of file REMORA_DataStruct.H.
Referenced by display(), init_params(), and REMORA::setup_step().
use_uv3dmix
bool SolverChoice::use_uv3dmix = true
Definition at line 548 of file REMORA_DataStruct.H.
Referenced by display(), init_params(), and REMORA::setup_step().
uv_Hadv_scheme
AdvectionScheme SolverChoice::uv_Hadv_scheme
Definition at line 572 of file REMORA_DataStruct.H.
Referenced by display(), init_params(), REMORA::rhs_uv_2d(), and REMORA::rhs_uv_3d().
vert_mixing_type
VertMixingType SolverChoice::vert_mixing_type
Definition at line 599 of file REMORA_DataStruct.H.
Referenced by REMORA::advance_3d(), init_params(), REMORA::init_set_vmix(), REMORA::init_stuff(), REMORA::ReadCheckpointFile(), REMORA::setup_step(), and REMORA::WriteCheckpointFile().
visc2
amrex::Real SolverChoice::visc2 = amrex::Real(0.0)
Definition at line 660 of file REMORA_DataStruct.H.
Referenced by init_params(), and REMORA::set_hmixcoef().
wind_type
WindType SolverChoice::wind_type
Definition at line 587 of file REMORA_DataStruct.H.
Referenced by REMORA::init_only(), init_params(), and REMORA::set_wind().
Zob
amrex::Real SolverChoice::Zob = amrex::Real(2e-2)
Definition at line 617 of file REMORA_DataStruct.H.
Referenced by init_params(), and REMORA::init_stuff().
Zos
amrex::Real SolverChoice::Zos = amrex::Real(2e-2)
Definition at line 618 of file REMORA_DataStruct.H.
Referenced by REMORA::gls_corrector(), and init_params().
The documentation for this struct was generated from the following file:
/home/runner/work/REMORA/REMORA/Source/REMORA_DataStruct.H