var searchData=
[
  ['r0_0',['R0',['../structSolverChoice.html#a7f081843ab68cd0a410afd74a27dfc30',1,'SolverChoice']]],
  ['r4_1',['r4',['../namespacemod__kinds.html#a2460f9692ecd4e49acbb4a3ba9c2c775',1,'mod_kinds']]],
  ['r8_2',['r8',['../namespacemod__kinds.html#a4f689f1fc8a76792eeeea610e89a0c4a',1,'mod_kinds']]],
  ['r_5fp2n_3',['R_P2N',['../structREMORABiology_1_1FennelParameters.html#a72605afe6f37ca796a689e9d0ddc1e52',1,'REMORABiology::FennelParameters']]],
  ['rain_4',['rain',['../namespaceAtmosState.html#a76d13f6889b52b16bc3d9680db35206eae5b6e68ed0fb29d473a29bc510a1ba03',1,'AtmosState::Rain'],['../namespaceAtmosFluxes.html#ac91c9b5d225271b3908b098cf63ed9e6a65abad4445aa6739d93a760407ffa235',1,'AtmosFluxes::Rain'],['../namespaceBulkFlux.html#ab4d324d7d6b4886cca281114c64ba588af2b8d1353e858319dcc1bb5471d962a4',1,'BulkFlux::Rain'],['../structSolverChoice.html#a9ac46247923ff034df732112a0815522',1,'SolverChoice::rain']]],
  ['rain_5fdata_5ffrom_5ffile_5',['rain_data_from_file',['../classREMORA.html#a21b0d6d04d3efc4e4171dadea7513c4f',1,'REMORA']]],
  ['rdec_6',['rdec',['../structREMORABiology_1_1Fennel_1_1Components.html#a6ddd41a730fdc0a1b546cf2e1d4672a6',1,'REMORABiology::Fennel::Components']]],
  ['rden_7',['rden',['../structREMORABiology_1_1Fennel_1_1Components.html#ad14cc515ef69035d59e933ca1e9e091b',1,'REMORABiology::Fennel::Components']]],
  ['rderrc_8',['RDeRRC',['../structREMORABiology_1_1FennelParameters.html#a669905a8f2c2bd2b387b7dda628db313',1,'REMORABiology::FennelParameters']]],
  ['rderrn_9',['RDeRRN',['../structREMORABiology_1_1FennelParameters.html#ab95ac90aa93ee47026ee237207680811',1,'REMORABiology::FennelParameters']]],
  ['rdrag_10',['rdrag',['../structSolverChoice.html#ab32c6e7161ddf37e8051743fae717cf5',1,'SolverChoice']]],
  ['rdrag2_11',['rdrag2',['../structSolverChoice.html#a276a75afbc3aa0e75227cb60c6901d31',1,'SolverChoice']]],
  ['read_5fbathymetry_5ffrom_5fnetcdf_12',['read_bathymetry_from_netcdf',['../REMORA__init__from__netcdf_8cpp.html#a495279fa35a077651a2257d6a760e707',1,'read_bathymetry_from_netcdf(int lev, const Box &amp;domain, const std::string &amp;fname, FArrayBox &amp;NC_h_fab):&#160;REMORA_ReadFromInitNetcdf.cpp'],['../REMORA__ReadFromInitNetcdf_8cpp.html#a32da5d352db1b3a382b5103613488083',1,'read_bathymetry_from_netcdf(int, const Box &amp;domain, const std::string &amp;fname, FArrayBox &amp;NC_h_fab):&#160;REMORA_ReadFromInitNetcdf.cpp']]],
  ['read_5fbathymetry_5ffull_5fdomain_5ffrom_5fnetcdf_13',['read_bathymetry_full_domain_from_netcdf',['../REMORA__init__from__netcdf_8cpp.html#a6c189eca2928ce27b82e38ae0505fed6',1,'read_bathymetry_full_domain_from_netcdf(const Box &amp;domain, const std::string &amp;fname, FArrayBox &amp;NC_h_fab, IntVect ngrow):&#160;REMORA_ReadFromInitNetcdf.cpp'],['../REMORA__ReadFromInitNetcdf_8cpp.html#a6c189eca2928ce27b82e38ae0505fed6',1,'read_bathymetry_full_domain_from_netcdf(const Box &amp;domain, const std::string &amp;fname, FArrayBox &amp;NC_h_fab, IntVect ngrow):&#160;REMORA_ReadFromInitNetcdf.cpp']]],
  ['read_5fbiology_5ffrom_5fnetcdf_14',['read_biology_from_netcdf',['../REMORA__init__from__netcdf_8cpp.html#a69bb9bb11d758d2e73c718aa384cb6c4',1,'read_biology_from_netcdf(int, const Box &amp;domain, const std::string &amp;fname, const Vector&lt; std::string &gt; &amp;biology_names, Vector&lt; FArrayBox &gt; &amp;NC_biology_fab):&#160;REMORA_ReadFromInitNetcdf.cpp'],['../REMORA__ReadFromInitNetcdf_8cpp.html#a69bb9bb11d758d2e73c718aa384cb6c4',1,'read_biology_from_netcdf(int, const Box &amp;domain, const std::string &amp;fname, const Vector&lt; std::string &gt; &amp;biology_names, Vector&lt; FArrayBox &gt; &amp;NC_biology_fab):&#160;REMORA_ReadFromInitNetcdf.cpp']]],
  ['read_5fbiology_5ffull_5fdomain_5ffrom_5fnetcdf_15',['read_biology_full_domain_from_netcdf',['../REMORA__init__from__netcdf_8cpp.html#a7df46640ff1f1386c66fe17f23b7efa1',1,'read_biology_full_domain_from_netcdf(int, const Box &amp;domain, const std::string &amp;fname, const Vector&lt; std::string &gt; &amp;biology_names, Vector&lt; FArrayBox &gt; &amp;NC_biology_fab, IntVect ngrow):&#160;REMORA_ReadFromInitNetcdf.cpp'],['../REMORA__ReadFromInitNetcdf_8cpp.html#a7df46640ff1f1386c66fe17f23b7efa1',1,'read_biology_full_domain_from_netcdf(int, const Box &amp;domain, const std::string &amp;fname, const Vector&lt; std::string &gt; &amp;biology_names, Vector&lt; FArrayBox &gt; &amp;NC_biology_fab, IntVect ngrow):&#160;REMORA_ReadFromInitNetcdf.cpp']]],
  ['read_5fclim_5fnudg_5fcoeff_5ffrom_5fnetcdf_16',['read_clim_nudg_coeff_from_netcdf',['../REMORA__init__from__netcdf_8cpp.html#af4db9610cd25c5252655cb413dbefebe',1,'read_clim_nudg_coeff_from_netcdf(int lev, const Box &amp;domain, const std::string &amp;fname, bool do_m2_clim_nudg, bool do_m3_clim_nudg, const amrex::Vector&lt; int &gt; &amp;do_cons_clim_nudg, const amrex::Vector&lt; std::string &gt; &amp;cons_names, FArrayBox &amp;NC_M2NC_fab, FArrayBox &amp;NC_M3NC_fab, amrex::Vector&lt; FArrayBox &gt; &amp;NC_ConsNC_fab, amrex::Vector&lt; int &gt; &amp;cons_coeff_in_file):&#160;REMORA_ReadFromInitNetcdf.cpp'],['../REMORA__ReadFromInitNetcdf_8cpp.html#a78ed1c40d6040aa260a266c4c8a2d2de',1,'read_clim_nudg_coeff_from_netcdf(int, const Box &amp;domain, const std::string &amp;fname, bool do_m2_clim_nudg, bool do_m3_clim_nudg, const amrex::Vector&lt; int &gt; &amp;do_cons_clim_nudg, const amrex::Vector&lt; std::string &gt; &amp;cons_names, FArrayBox &amp;NC_M2NC_fab, FArrayBox &amp;NC_M3NC_fab, amrex::Vector&lt; FArrayBox &gt; &amp;NC_ConsNC_fab, amrex::Vector&lt; int &gt; &amp;cons_coeff_in_file):&#160;REMORA_ReadFromInitNetcdf.cpp']]],
  ['read_5fcoriolis_5ffrom_5fnetcdf_17',['read_coriolis_from_netcdf',['../REMORA__init__from__netcdf_8cpp.html#a1dd851a61f8e589599a1e0a7c276e062',1,'read_coriolis_from_netcdf(int lev, const Box &amp;domain, const std::string &amp;fname, FArrayBox &amp;NC_fcor_fab):&#160;REMORA_ReadFromInitNetcdf.cpp'],['../REMORA__ReadFromInitNetcdf_8cpp.html#a7a6597f4ecb34b220dd5aa257d91a7cb',1,'read_coriolis_from_netcdf(int, const Box &amp;domain, const std::string &amp;fname, FArrayBox &amp;NC_fcor_fab):&#160;REMORA_ReadFromInitNetcdf.cpp']]],
  ['read_5fdata_5ffrom_5fnetcdf_18',['read_data_from_netcdf',['../REMORA__ReadFromInitNetcdf_8cpp.html#ab1a69ac8e35d33f521b18d25577964f2',1,'read_data_from_netcdf(int, const Box &amp;domain, const std::string &amp;fname, FArrayBox &amp;NC_temp_fab, FArrayBox &amp;NC_salt_fab, FArrayBox &amp;NC_xvel_fab, FArrayBox &amp;NC_yvel_fab):&#160;REMORA_ReadFromInitNetcdf.cpp'],['../REMORA__init__from__netcdf_8cpp.html#ab1a69ac8e35d33f521b18d25577964f2',1,'read_data_from_netcdf(int, const Box &amp;domain, const std::string &amp;fname, FArrayBox &amp;NC_temp_fab, FArrayBox &amp;NC_salt_fab, FArrayBox &amp;NC_xvel_fab, FArrayBox &amp;NC_yvel_fab):&#160;REMORA_ReadFromInitNetcdf.cpp']]],
  ['read_5fdata_5ffull_5fdomain_5ffrom_5fnetcdf_19',['read_data_full_domain_from_netcdf',['../REMORA__init__from__netcdf_8cpp.html#a54ccc5a5efd8bcbe62e36977d87b4cce',1,'read_data_full_domain_from_netcdf(int, const Box &amp;domain, const std::string &amp;fname, FArrayBox &amp;NC_temp_fab, FArrayBox &amp;NC_salt_fab, FArrayBox &amp;NC_xvel_fab, FArrayBox &amp;NC_yvel_fab, IntVect ngrow):&#160;REMORA_ReadFromInitNetcdf.cpp'],['../REMORA__ReadFromInitNetcdf_8cpp.html#a54ccc5a5efd8bcbe62e36977d87b4cce',1,'read_data_full_domain_from_netcdf(int, const Box &amp;domain, const std::string &amp;fname, FArrayBox &amp;NC_temp_fab, FArrayBox &amp;NC_salt_fab, FArrayBox &amp;NC_xvel_fab, FArrayBox &amp;NC_yvel_fab, IntVect ngrow):&#160;REMORA_ReadFromInitNetcdf.cpp']]],
  ['read_5fgrid_5fvars_5ffrom_5fnetcdf_20',['read_grid_vars_from_netcdf',['../REMORA__ReadFromInitNetcdf_8cpp.html#a5ee5c7322b2ce0c02e202994ca8833da',1,'read_grid_vars_from_netcdf(int, const Box &amp;domain, const std::string &amp;fname, FArrayBox &amp;NC_pm_fab, FArrayBox &amp;NC_pn_fab, FArrayBox &amp;NC_xr_fab, FArrayBox &amp;NC_yr_fab, FArrayBox &amp;NC_xu_fab, FArrayBox &amp;NC_yu_fab, FArrayBox &amp;NC_xv_fab, FArrayBox &amp;NC_yv_fab, FArrayBox &amp;NC_xp_fab, FArrayBox &amp;NC_yp_fab):&#160;REMORA_ReadFromInitNetcdf.cpp'],['../REMORA__init__from__netcdf_8cpp.html#a1f2fea32cf46e4d433b5bf3ca3ba7828',1,'read_grid_vars_from_netcdf(int lev, const Box &amp;domain, const std::string &amp;fname, FArrayBox &amp;NC_pm_fab, FArrayBox &amp;NC_pn_fab, FArrayBox &amp;NC_xr_fab, FArrayBox &amp;NC_yr_fab, FArrayBox &amp;NC_xu_fab, FArrayBox &amp;NC_yu_fab, FArrayBox &amp;NC_xv_fab, FArrayBox &amp;NC_yv_fab, FArrayBox &amp;NC_xp_fab, FArrayBox &amp;NC_yp_fab):&#160;REMORA_ReadFromInitNetcdf.cpp']]],
  ['read_5fgrid_5fvars_5ffull_5fdomain_5ffrom_5fnetcdf_21',['read_grid_vars_full_domain_from_netcdf',['../REMORA__ReadFromInitNetcdf_8cpp.html#aec1c389b9822a484c2fc252d290b8deb',1,'read_grid_vars_full_domain_from_netcdf(const Box &amp;domain, const std::string &amp;fname, FArrayBox &amp;NC_pm_fab, FArrayBox &amp;NC_pn_fab, IntVect ngrow):&#160;REMORA_ReadFromInitNetcdf.cpp'],['../REMORA__init__from__netcdf_8cpp.html#aec1c389b9822a484c2fc252d290b8deb',1,'read_grid_vars_full_domain_from_netcdf(const Box &amp;domain, const std::string &amp;fname, FArrayBox &amp;NC_pm_fab, FArrayBox &amp;NC_pn_fab, IntVect ngrow):&#160;REMORA_ReadFromInitNetcdf.cpp']]],
  ['read_5fin_5fat_5ftime_22',['read_in_at_time',['../classNCTimeSeries.html#a297437358973471709cbec9de11a24bb',1,'NCTimeSeries::read_in_at_time()'],['../classNCTimeSeriesBoundary.html#aa59234163bfc966da5e57d66865745b4',1,'NCTimeSeriesBoundary::read_in_at_time()'],['../classNCTimeSeriesRiver.html#abf586562cf93e68e604212666f66bf31',1,'NCTimeSeriesRiver::read_in_at_time()']]],
  ['read_5fmasks_5ffrom_5fnetcdf_23',['read_masks_from_netcdf',['../REMORA__ReadFromInitNetcdf_8cpp.html#a7b728f24fbad6791f280538ce240c523',1,'read_masks_from_netcdf(int, const Box &amp;domain, const std::string &amp;fname, FArrayBox &amp;NC_mskr_fab, FArrayBox &amp;NC_msku_fab, FArrayBox &amp;NC_mskv_fab):&#160;REMORA_ReadFromInitNetcdf.cpp'],['../REMORA__init__from__netcdf_8cpp.html#a7b728f24fbad6791f280538ce240c523',1,'read_masks_from_netcdf(int, const Box &amp;domain, const std::string &amp;fname, FArrayBox &amp;NC_mskr_fab, FArrayBox &amp;NC_msku_fab, FArrayBox &amp;NC_mskv_fab):&#160;REMORA_ReadFromInitNetcdf.cpp']]],
  ['read_5fscalars_5ffrom_5fnetcdf_24',['read_scalars_from_netcdf',['../REMORA__ReadFromInitNetcdf_8cpp.html#ac00c3e32f5a064a7dd298f031295590a',1,'read_scalars_from_netcdf(int, const Box &amp;domain, const std::string &amp;fname, const Vector&lt; std::string &gt; &amp;scalar_names, Vector&lt; FArrayBox &gt; &amp;NC_scalar_fab, Vector&lt; int &gt; &amp;scalar_in_file):&#160;REMORA_ReadFromInitNetcdf.cpp'],['../REMORA__init__from__netcdf_8cpp.html#ac00c3e32f5a064a7dd298f031295590a',1,'read_scalars_from_netcdf(int, const Box &amp;domain, const std::string &amp;fname, const Vector&lt; std::string &gt; &amp;scalar_names, Vector&lt; FArrayBox &gt; &amp;NC_scalar_fab, Vector&lt; int &gt; &amp;scalar_in_file):&#160;REMORA_ReadFromInitNetcdf.cpp']]],
  ['read_5fscalars_5ffull_5fdomain_5ffrom_5fnetcdf_25',['read_scalars_full_domain_from_netcdf',['../REMORA__init__from__netcdf_8cpp.html#a53e39809d0043c74fd5799ef3b98b6b4',1,'read_scalars_full_domain_from_netcdf(int, const Box &amp;domain, const std::string &amp;fname, const Vector&lt; std::string &gt; &amp;scalar_names, Vector&lt; FArrayBox &gt; &amp;NC_scalar_fab, Vector&lt; int &gt; &amp;scalar_in_file, IntVect ngrow):&#160;REMORA_ReadFromInitNetcdf.cpp'],['../REMORA__ReadFromInitNetcdf_8cpp.html#a53e39809d0043c74fd5799ef3b98b6b4',1,'read_scalars_full_domain_from_netcdf(int, const Box &amp;domain, const std::string &amp;fname, const Vector&lt; std::string &gt; &amp;scalar_names, Vector&lt; FArrayBox &gt; &amp;NC_scalar_fab, Vector&lt; int &gt; &amp;scalar_in_file, IntVect ngrow):&#160;REMORA_ReadFromInitNetcdf.cpp']]],
  ['read_5fspherical_5fgrid_5fvars_5ffrom_5fnetcdf_26',['read_spherical_grid_vars_from_netcdf',['../REMORA__init__from__netcdf_8cpp.html#add2a51b313d6c0189cfce4bead514011',1,'read_spherical_grid_vars_from_netcdf(int lev, const Box &amp;domain, const std::string &amp;fname, FArrayBox &amp;NC_lonp_fab, FArrayBox &amp;NC_latp_fab):&#160;REMORA_ReadFromInitNetcdf.cpp'],['../REMORA__ReadFromInitNetcdf_8cpp.html#aa564069a43b5e2da32ffb41552b5495b',1,'read_spherical_grid_vars_from_netcdf(int, const Box &amp;domain, const std::string &amp;fname, FArrayBox &amp;NC_lonp_fab, FArrayBox &amp;NC_latp_fab):&#160;REMORA_ReadFromInitNetcdf.cpp']]],
  ['read_5fvec_5ffrom_5fnetcdf_27',['read_vec_from_netcdf',['../REMORA__init__from__netcdf_8cpp.html#a137cd9c9888645dff2f751f8f1eb34a1',1,'read_vec_from_netcdf(int lev, const amrex::Vector&lt; std::string &gt; &amp;fnames, const std::string &amp;field_name, amrex::Vector&lt; int &gt; &amp;vec_dat):&#160;REMORA_ReadFromInitNetcdf.cpp'],['../REMORA__ReadFromInitNetcdf_8cpp.html#a3da36b397933adf369b4577e633d75ad',1,'read_vec_from_netcdf(int, const amrex::Vector&lt; std::string &gt; &amp;fnames, const std::string &amp;field_name, amrex::Vector&lt; int &gt; &amp;vec_dat):&#160;REMORA_ReadFromInitNetcdf.cpp']]],
  ['read_5fzeta_5ffrom_5fnetcdf_28',['read_zeta_from_netcdf',['../REMORA__init__from__netcdf_8cpp.html#a3b79d2046e177b1deb8fcfa247e3e302',1,'read_zeta_from_netcdf(int lev, const Box &amp;domain, const std::string &amp;fname, FArrayBox &amp;NC_zeta_fab):&#160;REMORA_ReadFromInitNetcdf.cpp'],['../REMORA__ReadFromInitNetcdf_8cpp.html#a93abfd752f08163f171e4aae8649b6c1',1,'read_zeta_from_netcdf(int, const Box &amp;domain, const std::string &amp;fname, FArrayBox &amp;NC_zeta_fab):&#160;REMORA_ReadFromInitNetcdf.cpp']]],
  ['read_5fzeta_5ffull_5fdomain_5ffrom_5fnetcdf_29',['read_zeta_full_domain_from_netcdf',['../REMORA__init__from__netcdf_8cpp.html#ab5f564829c85a471db5bbb662aeae15b',1,'read_zeta_full_domain_from_netcdf(int lev, const Box &amp;domain, const std::string &amp;fname, FArrayBox &amp;NC_zeta_fab, IntVect ngrow):&#160;REMORA_ReadFromInitNetcdf.cpp'],['../REMORA__ReadFromInitNetcdf_8cpp.html#a1fb3cc10225716b9d1d2578b35ba2951',1,'read_zeta_full_domain_from_netcdf(int, const Box &amp;domain, const std::string &amp;fname, FArrayBox &amp;NC_zeta_fab, IntVect ngrow):&#160;REMORA_ReadFromInitNetcdf.cpp']]],
  ['readcheckpointfile_30',['ReadCheckpointFile',['../classREMORA.html#a316a6db4c0b9a218e834c054d8c8f437',1,'REMORA']]],
  ['readncmultifab_31',['ReadNCMultiFab',['../classREMORA.html#ab769980f39311ba1114edf815286c40a',1,'REMORA']]],
  ['readnetcdffile_32',['ReadNetCDFFile',['../REMORA__NCFile_8H.html#a3e720d7f1573b1b0c7cb9a0b7b8bb871',1,'REMORA_NCFile.H']]],
  ['readnetcdfvarattrstr_33',['readnetcdfvarattrstr',['../REMORA__NCFile_8cpp.html#af8eb0b5eb41bbbf48a6dbced8cd0d6ea',1,'ReadNetCDFVarAttrStr(const std::string &amp;fname, const std::string &amp;var_name, const std::string &amp;attr_name):&#160;REMORA_NCFile.cpp'],['../REMORA__NCFile_8H.html#af8eb0b5eb41bbbf48a6dbced8cd0d6ea',1,'ReadNetCDFVarAttrStr(const std::string &amp;fname, const std::string &amp;var_name, const std::string &amp;attr_name):&#160;REMORA_NCFile.cpp']]],
  ['readparameters_34',['ReadParameters',['../classREMORA.html#aae1b7a86e03c93dd71e2d68c700d2512',1,'REMORA']]],
  ['real_35',['Real',['../structncutils_1_1NCDType.html#a7a5be35daa7dbb2cc72507cc4b5a422c',1,'ncutils::NCDType']]],
  ['ref_5ftags_36',['ref_tags',['../classREMORA.html#a476b854ad74dd35ec1bf21cd9ea1f0b0',1,'REMORA']]],
  ['refined_20adaptively_20built_20on_20amrex_20_3a_20remora_37',['Regional Modeling of Oceans Refined Adaptively (built on AMReX): REMORA',['../index.html',1,'']]],
  ['refinement_38',['Adaptive Mesh Refinement',['../index.html#amr',1,'']]],
  ['refinement_5fcriteria_5fsetup_39',['refinement_criteria_setup',['../classREMORA.html#a6da8127bba6a3636d4f5ae30983eaf9c',1,'REMORA']]],
  ['reflect_5feven_40',['reflect_even',['../namespaceREMORABCType.html#ac0d18d4bb218d5950db1000ef1abf346aaf8c10264d04dea51594afe39fd3c8a1',1,'REMORABCType']]],
  ['reflect_5fodd_41',['reflect_odd',['../namespaceREMORABCType.html#ac0d18d4bb218d5950db1000ef1abf346a9d34de510d9acde35ba5ebe70aa11cde',1,'REMORABCType']]],
  ['regional_20modeling_20of_20oceans_20refined_20adaptively_20built_20on_20amrex_20_3a_20remora_42',['Regional Modeling of Oceans Refined Adaptively (built on AMReX): REMORA',['../index.html',1,'']]],
  ['registercoarsedata_43',['RegisterCoarseData',['../classREMORAFillPatcher.html#a5177a51aceb8cc0293a855ad71f03bdc',1,'REMORAFillPatcher']]],
  ['regrid_5fint_44',['regrid_int',['../classREMORA.html#a5d3ceaf421e5e6ec42b4da2fcb2d610c',1,'REMORA']]],
  ['remakelevel_45',['RemakeLevel',['../classREMORA.html#a73eb64a4ad24a247692981eae835caf2',1,'REMORA']]],
  ['remora_46',['remora',['../index.html',1,'Regional Modeling of Oceans Refined Adaptively (built on AMReX): REMORA'],['../classREMORA.html#a2e6c44c76a0dca92869a64f7f8d06fac',1,'REMORA::REMORA(const amrex::RealBox &amp;rb, int max_level_in, const amrex::Vector&lt; int &gt; &amp;n_cell_in, int coord, const amrex::Vector&lt; amrex::IntVect &gt; &amp;ref_ratio, const amrex::Array&lt; int, AMREX_SPACEDIM &gt; &amp;is_per, std::string prefix)'],['../classREMORA.html#a8a16e552c794ae05498e4cb0a65399af',1,'REMORA::REMORA()'],['../classREMORA.html',1,'REMORA']]],
  ['remora_2ecpp_47',['REMORA.cpp',['../REMORA_8cpp.html',1,'']]],
  ['remora_2eh_48',['REMORA.H',['../REMORA_8H.html',1,'']]],
  ['remora_5fadvance_49',['remora_advance',['../classREMORA.html#a6f50a7999b5955331392139cfb09ad27',1,'REMORA']]],
  ['remora_5fadvance_2ecpp_50',['REMORA_Advance.cpp',['../REMORA__Advance_8cpp.html',1,'']]],
  ['remora_5fadvance_5f2d_2ecpp_51',['REMORA_advance_2d.cpp',['../REMORA__advance__2d_8cpp.html',1,'']]],
  ['remora_5fadvance_5f2d_5fonestep_2ecpp_52',['REMORA_advance_2d_onestep.cpp',['../REMORA__advance__2d__onestep_8cpp.html',1,'']]],
  ['remora_5fadvance_5f3d_2ecpp_53',['REMORA_advance_3d.cpp',['../REMORA__advance__3d_8cpp.html',1,'']]],
  ['remora_5fadvance_5f3d_5fml_2ecpp_54',['REMORA_advance_3d_ml.cpp',['../REMORA__advance__3d__ml_8cpp.html',1,'']]],
  ['remora_5fapply_5fclim_5fnudg_2ecpp_55',['REMORA_apply_clim_nudg.cpp',['../REMORA__apply__clim__nudg_8cpp.html',1,'']]],
  ['remora_5fbc_56',['REMORA_BC',['../REMORA__IndexDefines_8H.html#a4a23ce64320a8ee19b456144f4deb325',1,'REMORA_IndexDefines.H']]],
  ['remora_5fbiology_2ecpp_57',['REMORA_Biology.cpp',['../REMORA__Biology_8cpp.html',1,'']]],
  ['remora_5fbiology_2eh_58',['REMORA_Biology.H',['../REMORA__Biology_8H.html',1,'']]],
  ['remora_5fboundaryconditions_5fcons_2ecpp_59',['REMORA_BoundaryConditions_cons.cpp',['../REMORA__BoundaryConditions__cons_8cpp.html',1,'']]],
  ['remora_5fboundaryconditions_5fnetcdf_2ecpp_60',['REMORA_BoundaryConditions_netcdf.cpp',['../REMORA__BoundaryConditions__netcdf_8cpp.html',1,'']]],
  ['remora_5fboundaryconditions_5fxvel_2ecpp_61',['REMORA_BoundaryConditions_xvel.cpp',['../REMORA__BoundaryConditions__xvel_8cpp.html',1,'']]],
  ['remora_5fboundaryconditions_5fyvel_2ecpp_62',['REMORA_BoundaryConditions_yvel.cpp',['../REMORA__BoundaryConditions__yvel_8cpp.html',1,'']]],
  ['remora_5fboundaryconditions_5fzvel_2ecpp_63',['REMORA_BoundaryConditions_zvel.cpp',['../REMORA__BoundaryConditions__zvel_8cpp.html',1,'']]],
  ['remora_5fbulk_5fflux_2ecpp_64',['REMORA_bulk_flux.cpp',['../REMORA__bulk__flux_8cpp.html',1,'']]],
  ['remora_5fbulk_5fflux_5ftest_2ecpp_65',['REMORA_bulk_flux_test.cpp',['../REMORA__bulk__flux__test_8cpp.html',1,'']]],
  ['remora_5fcaldate_66',['remora_caldate',['../REMORA__DateClock_8H.html#ae651edb568cb47f0556b8d5fee20e7f5',1,'remora_caldate(amrex::Real time_ref, amrex::Real current_time_days, int &amp;year, amrex::Real &amp;yday) noexcept:&#160;REMORA_DateClock.H'],['../REMORA__DateClock_8H.html#a664ef4996854c3f6b424b33bf559aa7d',1,'remora_caldate(amrex::Real time_ref, amrex::Real current_time_days, int &amp;year, int &amp;month, int &amp;day, amrex::Real &amp;yday) noexcept:&#160;REMORA_DateClock.H']]],
  ['remora_5fcheckpoint_2ecpp_67',['REMORA_Checkpoint.cpp',['../REMORA__Checkpoint_8cpp.html',1,'']]],
  ['remora_5fcomputetimestep_2ecpp_68',['REMORA_ComputeTimestep.cpp',['../REMORA__ComputeTimestep_8cpp.html',1,'']]],
  ['remora_5fconsole_5fio_2ecpp_69',['REMORA_console_io.cpp',['../REMORA__console__io_8cpp.html',1,'']]],
  ['remora_5fconstants_2eh_70',['REMORA_Constants.H',['../REMORA__Constants_8H.html',1,'']]],
  ['remora_5fcoriolis_2ecpp_71',['REMORA_coriolis.cpp',['../REMORA__coriolis_8cpp.html',1,'']]],
  ['remora_5fcoupling_2ecpp_72',['REMORA_Coupling.cpp',['../REMORA__Coupling_8cpp.html',1,'']]],
  ['remora_5fcurvilinear_2ecpp_73',['REMORA_curvilinear.cpp',['../REMORA__curvilinear_8cpp.html',1,'']]],
  ['remora_5fdatastruct_2eh_74',['REMORA_DataStruct.H',['../REMORA__DataStruct_8H.html',1,'']]],
  ['remora_5fdateclock_2eh_75',['REMORA_DateClock.H',['../REMORA__DateClock_8H.html',1,'']]],
  ['remora_5fdatenum_76',['remora_datenum',['../REMORA__DateClock_8H.html#ae94ae5ede9323e0970aad8ed1341ccec',1,'REMORA_DateClock.H']]],
  ['remora_5fdatevec_77',['remora_datevec',['../REMORA__DateClock_8H.html#a0679079b26cea665d983a3165d655d9f',1,'REMORA_DateClock.H']]],
  ['remora_5fdepthstretchtransform_2eh_78',['REMORA_DepthStretchTransform.H',['../REMORA__DepthStretchTransform_8H.html',1,'']]],
  ['remora_5fderive_2ecpp_79',['REMORA_Derive.cpp',['../REMORA__Derive_8cpp.html',1,'']]],
  ['remora_5fderive_2eh_80',['REMORA_Derive.H',['../REMORA__Derive_8H.html',1,'']]],
  ['remora_5fdernull_81',['remora_dernull',['../namespacederived.html#a2457359b34a83452a2d6d602f9919ae3',1,'derived']]],
  ['remora_5fdervort_82',['remora_dervort',['../namespacederived.html#a0e96290f839430c45b60d3bde88696ec',1,'derived']]],
  ['remora_5ffennel_5ffortran_5finterface_2eh_83',['REMORA_Fennel_Fortran_Interface.H',['../REMORA__Fennel__Fortran__Interface_8H.html',1,'']]],
  ['remora_5ffennel_5fisohelper_84',['remora_fennel_isohelper',['../namespaceremora__fennel__isohelper.html',1,'']]],
  ['remora_5ffennel_5froms_2ef_85',['REMORA_fennel_roms.F',['../REMORA__fennel__roms_8F.html',1,'']]],
  ['remora_5ffennelbridge_2ecpp_86',['REMORA_FennelBridge.cpp',['../REMORA__FennelBridge_8cpp.html',1,'']]],
  ['remora_5ffillpatch_2ecpp_87',['REMORA_FillPatch.cpp',['../REMORA__FillPatch_8cpp.html',1,'']]],
  ['remora_5ffillpatcher_2ecpp_88',['REMORA_FillPatcher.cpp',['../REMORA__FillPatcher_8cpp.html',1,'']]],
  ['remora_5ffillpatcher_2eh_89',['REMORA_FillPatcher.H',['../REMORA__FillPatcher_8H.html',1,'']]],
  ['remora_5ffunwave_5fadvance_2ef90_90',['REMORA_funwave_advance.F90',['../REMORA__funwave__advance_8F90.html',1,'']]],
  ['remora_5ffunwave_5ffortran_5finterface_2eh_91',['REMORA_funwave_Fortran_Interface.H',['../REMORA__funwave__Fortran__Interface_8H.html',1,'']]],
  ['remora_5ffunwave_5fisohelper_92',['remora_funwave_isohelper',['../namespaceremora__funwave__isohelper.html',1,'']]],
  ['remora_5ffunwave_5fisohelper_2ef90_93',['REMORA_funwave_isohelper.F90',['../REMORA__funwave__isohelper_8F90.html',1,'']]],
  ['remora_5fgls_2ecpp_94',['REMORA_gls.cpp',['../REMORA__gls_8cpp.html',1,'']]],
  ['remora_5fgregorian_5fdaynum_95',['remora_gregorian_daynum',['../REMORA__DateClock_8H.html#a5790a3c2a97927b6001bad7dbe45f8fa',1,'REMORA_DateClock.H']]],
  ['remora_5findexdefines_2eh_96',['REMORA_IndexDefines.H',['../REMORA__IndexDefines_8H.html',1,'']]],
  ['remora_5finit_2ecpp_97',['REMORA_init.cpp',['../REMORA__init_8cpp.html',1,'']]],
  ['remora_5finit1d_2ecpp_98',['REMORA_init1d.cpp',['../REMORA__init1d_8cpp.html',1,'']]],
  ['remora_5finit_5fbcs_2ecpp_99',['REMORA_init_bcs.cpp',['../REMORA__init__bcs_8cpp.html',1,'']]],
  ['remora_5finit_5ffrom_5fnetcdf_2ecpp_100',['REMORA_init_from_netcdf.cpp',['../REMORA__init__from__netcdf_8cpp.html',1,'']]],
  ['remora_5finitanalyticbathymetry_5fadvection_2eh_101',['REMORA_InitAnalyticBathymetry_Advection.H',['../REMORA__InitAnalyticBathymetry__Advection_8H.html',1,'']]],
  ['remora_5finitanalyticbathymetry_5fboundarylayer_2eh_102',['REMORA_InitAnalyticBathymetry_BoundaryLayer.H',['../REMORA__InitAnalyticBathymetry__BoundaryLayer_8H.html',1,'']]],
  ['remora_5finitanalyticbathymetry_5fchanneltest_2eh_103',['REMORA_InitAnalyticBathymetry_ChannelTest.H',['../REMORA__InitAnalyticBathymetry__ChannelTest_8H.html',1,'']]],
  ['remora_5finitanalyticbathymetry_5fcoupletoerf_2eh_104',['REMORA_InitAnalyticBathymetry_CoupleToERF.H',['../REMORA__InitAnalyticBathymetry__CoupleToERF_8H.html',1,'']]],
  ['remora_5finitanalyticbathymetry_5fdogboneanalytic_2eh_105',['REMORA_InitAnalyticBathymetry_DogboneAnalytic.H',['../REMORA__InitAnalyticBathymetry__DogboneAnalytic_8H.html',1,'']]],
  ['remora_5finitanalyticbathymetry_5fdoublyperiodic_2eh_106',['REMORA_InitAnalyticBathymetry_DoublyPeriodic.H',['../REMORA__InitAnalyticBathymetry__DoublyPeriodic_8H.html',1,'']]],
  ['remora_5finitanalyticbathymetry_5fparticlesoverseamount_2eh_107',['REMORA_InitAnalyticBathymetry_ParticlesOverSeamount.H',['../REMORA__InitAnalyticBathymetry__ParticlesOverSeamount_8H.html',1,'']]],
  ['remora_5finitanalyticbathymetry_5fseamount_2eh_108',['REMORA_InitAnalyticBathymetry_Seamount.H',['../REMORA__InitAnalyticBathymetry__Seamount_8H.html',1,'']]],
  ['remora_5finitanalyticbathymetry_5fupwelling_2eh_109',['REMORA_InitAnalyticBathymetry_Upwelling.H',['../REMORA__InitAnalyticBathymetry__Upwelling_8H.html',1,'']]],
  ['remora_5finitanalyticbathymetry_5fupwelling_5fcoupling_2eh_110',['REMORA_InitAnalyticBathymetry_Upwelling_Coupling.H',['../REMORA__InitAnalyticBathymetry__Upwelling__Coupling_8H.html',1,'']]],
  ['remora_5finitanalyticbathymetry_5fupwelling_5fml_2eh_111',['REMORA_InitAnalyticBathymetry_Upwelling_ML.H',['../REMORA__InitAnalyticBathymetry__Upwelling__ML_8H.html',1,'']]],
  ['remora_5finitanalyticbiology_5fbiotoy_2eh_112',['REMORA_InitAnalyticBiology_BioToy.H',['../REMORA__InitAnalyticBiology__BioToy_8H.html',1,'']]],
  ['remora_5finitanalyticgridscale_5fboundarylayer_2eh_113',['REMORA_InitAnalyticGridScale_BoundaryLayer.H',['../REMORA__InitAnalyticGridScale__BoundaryLayer_8H.html',1,'']]],
  ['remora_5finitanalytichmix_5fadvection_2eh_114',['REMORA_InitAnalyticHMix_Advection.H',['../REMORA__InitAnalyticHMix__Advection_8H.html',1,'']]],
  ['remora_5finitanalytichmix_5fboundarylayer_2eh_115',['REMORA_InitAnalyticHMix_BoundaryLayer.H',['../REMORA__InitAnalyticHMix__BoundaryLayer_8H.html',1,'']]],
  ['remora_5finitanalytichmix_5fchanneltest_2eh_116',['REMORA_InitAnalyticHMix_ChannelTest.H',['../REMORA__InitAnalyticHMix__ChannelTest_8H.html',1,'']]],
  ['remora_5finitanalytichmix_5fdoublegyre_2eh_117',['REMORA_InitAnalyticHMix_DoubleGyre.H',['../REMORA__InitAnalyticHMix__DoubleGyre_8H.html',1,'']]],
  ['remora_5finitanalytichmix_5fdoublyperiodic_2eh_118',['REMORA_InitAnalyticHMix_DoublyPeriodic.H',['../REMORA__InitAnalyticHMix__DoublyPeriodic_8H.html',1,'']]],
  ['remora_5finitanalytichmix_5fidealminigrid_2eh_119',['REMORA_InitAnalyticHMix_IdealMiniGrid.H',['../REMORA__InitAnalyticHMix__IdealMiniGrid_8H.html',1,'']]],
  ['remora_5finitanalytichmix_5fidealrivgrid_2eh_120',['REMORA_InitAnalyticHMix_IdealRivGrid.H',['../REMORA__InitAnalyticHMix__IdealRivGrid_8H.html',1,'']]],
  ['remora_5finitanalytichmix_5fparticlesoverseamount_2eh_121',['REMORA_InitAnalyticHMix_ParticlesOverSeamount.H',['../REMORA__InitAnalyticHMix__ParticlesOverSeamount_8H.html',1,'']]],
  ['remora_5finitanalytichmix_5fseamount_2eh_122',['REMORA_InitAnalyticHMix_Seamount.H',['../REMORA__InitAnalyticHMix__Seamount_8H.html',1,'']]],
  ['remora_5finitanalytichmix_5fupwelling_2eh_123',['REMORA_InitAnalyticHMix_Upwelling.H',['../REMORA__InitAnalyticHMix__Upwelling_8H.html',1,'']]],
  ['remora_5finitanalytichmix_5fupwelling_5fml_2eh_124',['REMORA_InitAnalyticHMix_Upwelling_ML.H',['../REMORA__InitAnalyticHMix__Upwelling__ML_8H.html',1,'']]],
  ['remora_5finitanalyticmasks_5fdogboneanalytic_2eh_125',['REMORA_InitAnalyticMasks_DogboneAnalytic.H',['../REMORA__InitAnalyticMasks__DogboneAnalytic_8H.html',1,'']]],
  ['remora_5finitanalyticprob_5fadvection_2eh_126',['REMORA_InitAnalyticProb_Advection.H',['../REMORA__InitAnalyticProb__Advection_8H.html',1,'']]],
  ['remora_5finitanalyticprob_5fboundarylayer_2eh_127',['REMORA_InitAnalyticProb_BoundaryLayer.H',['../REMORA__InitAnalyticProb__BoundaryLayer_8H.html',1,'']]],
  ['remora_5finitanalyticprob_5fchanneltest_2eh_128',['REMORA_InitAnalyticProb_ChannelTest.H',['../REMORA__InitAnalyticProb__ChannelTest_8H.html',1,'']]],
  ['remora_5finitanalyticprob_5fcoupletoerf_2eh_129',['REMORA_InitAnalyticProb_CoupleToERF.H',['../REMORA__InitAnalyticProb__CoupleToERF_8H.html',1,'']]],
  ['remora_5finitanalyticprob_5fdogboneanalytic_2eh_130',['REMORA_InitAnalyticProb_DogboneAnalytic.H',['../REMORA__InitAnalyticProb__DogboneAnalytic_8H.html',1,'']]],
  ['remora_5finitanalyticprob_5fdoublegyre_2eh_131',['REMORA_InitAnalyticProb_DoubleGyre.H',['../REMORA__InitAnalyticProb__DoubleGyre_8H.html',1,'']]],
  ['remora_5finitanalyticprob_5fdoublyperiodic_2eh_132',['REMORA_InitAnalyticProb_DoublyPeriodic.H',['../REMORA__InitAnalyticProb__DoublyPeriodic_8H.html',1,'']]],
  ['remora_5finitanalyticprob_5fparticlesoverseamount_2eh_133',['REMORA_InitAnalyticProb_ParticlesOverSeamount.H',['../REMORA__InitAnalyticProb__ParticlesOverSeamount_8H.html',1,'']]],
  ['remora_5finitanalyticprob_5fseamount_2eh_134',['REMORA_InitAnalyticProb_Seamount.H',['../REMORA__InitAnalyticProb__Seamount_8H.html',1,'']]],
  ['remora_5finitanalyticprob_5fupwelling_2eh_135',['REMORA_InitAnalyticProb_Upwelling.H',['../REMORA__InitAnalyticProb__Upwelling_8H.html',1,'']]],
  ['remora_5finitanalyticprob_5fupwelling_5fcoupling_2eh_136',['REMORA_InitAnalyticProb_Upwelling_Coupling.H',['../REMORA__InitAnalyticProb__Upwelling__Coupling_8H.html',1,'']]],
  ['remora_5finitanalyticprob_5fupwelling_5fml_2eh_137',['REMORA_InitAnalyticProb_Upwelling_ML.H',['../REMORA__InitAnalyticProb__Upwelling__ML_8H.html',1,'']]],
  ['remora_5finitanalyticsmflux_5fchanneltest_2eh_138',['REMORA_InitAnalyticSMFlux_ChannelTest.H',['../REMORA__InitAnalyticSMFlux__ChannelTest_8H.html',1,'']]],
  ['remora_5finitanalyticsmflux_5fdoublegyre_2eh_139',['REMORA_InitAnalyticSMFlux_DoubleGyre.H',['../REMORA__InitAnalyticSMFlux__DoubleGyre_8H.html',1,'']]],
  ['remora_5finitanalyticsmflux_5fdoublyperiodic_2eh_140',['REMORA_InitAnalyticSMFlux_DoublyPeriodic.H',['../REMORA__InitAnalyticSMFlux__DoublyPeriodic_8H.html',1,'']]],
  ['remora_5finitanalyticsmflux_5fparticlesoverseamount_2eh_141',['REMORA_InitAnalyticSMFlux_ParticlesOverSeamount.H',['../REMORA__InitAnalyticSMFlux__ParticlesOverSeamount_8H.html',1,'']]],
  ['remora_5finitanalyticsmflux_5fupwelling_2eh_142',['REMORA_InitAnalyticSMFlux_Upwelling.H',['../REMORA__InitAnalyticSMFlux__Upwelling_8H.html',1,'']]],
  ['remora_5finitanalyticsmflux_5fupwellingml_2eh_143',['REMORA_InitAnalyticSMFlux_UpwellingML.H',['../REMORA__InitAnalyticSMFlux__UpwellingML_8H.html',1,'']]],
  ['remora_5finitanalyticsurfacevar_5fboundarylayer_2eh_144',['REMORA_InitAnalyticSurfaceVar_BoundaryLayer.H',['../REMORA__InitAnalyticSurfaceVar__BoundaryLayer_8H.html',1,'']]],
  ['remora_5finitanalyticvmix_5fadvection_2eh_145',['REMORA_InitAnalyticVMix_Advection.H',['../REMORA__InitAnalyticVMix__Advection_8H.html',1,'']]],
  ['remora_5finitanalyticvmix_5fboundarylayer_2eh_146',['REMORA_InitAnalyticVMix_BoundaryLayer.H',['../REMORA__InitAnalyticVMix__BoundaryLayer_8H.html',1,'']]],
  ['remora_5finitanalyticvmix_5fchanneltest_2eh_147',['REMORA_InitAnalyticVMix_ChannelTest.H',['../REMORA__InitAnalyticVMix__ChannelTest_8H.html',1,'']]],
  ['remora_5finitanalyticvmix_5fdoublegyre_2eh_148',['REMORA_InitAnalyticVMix_DoubleGyre.H',['../REMORA__InitAnalyticVMix__DoubleGyre_8H.html',1,'']]],
  ['remora_5finitanalyticvmix_5fdoublyperiodic_2eh_149',['REMORA_InitAnalyticVMix_DoublyPeriodic.H',['../REMORA__InitAnalyticVMix__DoublyPeriodic_8H.html',1,'']]],
  ['remora_5finitanalyticvmix_5fidealminigrid_2eh_150',['REMORA_InitAnalyticVMix_IdealMiniGrid.H',['../REMORA__InitAnalyticVMix__IdealMiniGrid_8H.html',1,'']]],
  ['remora_5finitanalyticvmix_5fidealrivgrid_2eh_151',['REMORA_InitAnalyticVMix_IdealRivGrid.H',['../REMORA__InitAnalyticVMix__IdealRivGrid_8H.html',1,'']]],
  ['remora_5finitanalyticvmix_5fparticlesoverseamount_2eh_152',['REMORA_InitAnalyticVMix_ParticlesOverSeamount.H',['../REMORA__InitAnalyticVMix__ParticlesOverSeamount_8H.html',1,'']]],
  ['remora_5finitanalyticvmix_5fseamount_2eh_153',['REMORA_InitAnalyticVMix_Seamount.H',['../REMORA__InitAnalyticVMix__Seamount_8H.html',1,'']]],
  ['remora_5finitanalyticvmix_5fupwelling_2eh_154',['REMORA_InitAnalyticVMix_Upwelling.H',['../REMORA__InitAnalyticVMix__Upwelling_8H.html',1,'']]],
  ['remora_5finitanalyticvmix_5fupwelling_5fml_2eh_155',['REMORA_InitAnalyticVMix_Upwelling_ML.H',['../REMORA__InitAnalyticVMix__Upwelling__ML_8H.html',1,'']]],
  ['remora_5finitanalyticvmix_5fupwellingml_2eh_156',['REMORA_InitAnalyticVMix_UpwellingML.H',['../REMORA__InitAnalyticVMix__UpwellingML_8H.html',1,'']]],
  ['remora_5finitanalyticzeta_5fdogboneanalytic_2eh_157',['REMORA_InitAnalyticZeta_DogboneAnalytic.H',['../REMORA__InitAnalyticZeta__DogboneAnalytic_8H.html',1,'']]],
  ['remora_5fmake_5fnew_5flevel_2ecpp_158',['REMORA_make_new_level.cpp',['../REMORA__make__new__level_8cpp.html',1,'']]],
  ['remora_5fmoab_2ecpp_159',['REMORA_MOAB.cpp',['../REMORA__MOAB_8cpp.html',1,'']]],
  ['remora_5fmoab_2eh_160',['REMORA_MOAB.H',['../REMORA__MOAB_8H.html',1,'']]],
  ['remora_5fncfile_2ecpp_161',['REMORA_NCFile.cpp',['../REMORA__NCFile_8cpp.html',1,'']]],
  ['remora_5fncfile_2eh_162',['REMORA_NCFile.H',['../REMORA__NCFile_8H.html',1,'']]],
  ['remora_5fncinterface_2ecpp_163',['REMORA_NCInterface.cpp',['../REMORA__NCInterface_8cpp.html',1,'']]],
  ['remora_5fncinterface_2eh_164',['REMORA_NCInterface.H',['../REMORA__NCInterface_8H.html',1,'']]],
  ['remora_5fncplotfile_2ecpp_165',['REMORA_NCPlotFile.cpp',['../REMORA__NCPlotFile_8cpp.html',1,'']]],
  ['remora_5fncplotfile_2eh_166',['REMORA_NCPlotFile.H',['../REMORA__NCPlotFile_8H.html',1,'']]],
  ['remora_5fnctimeseries_2ecpp_167',['REMORA_NCTimeSeries.cpp',['../REMORA__NCTimeSeries_8cpp.html',1,'']]],
  ['remora_5fnctimeseries_2eh_168',['REMORA_NCTimeSeries.H',['../REMORA__NCTimeSeries_8H.html',1,'']]],
  ['remora_5fnctimeseriesboundary_2ecpp_169',['REMORA_NCTimeSeriesBoundary.cpp',['../REMORA__NCTimeSeriesBoundary_8cpp.html',1,'']]],
  ['remora_5fnctimeseriesboundary_2eh_170',['REMORA_NCTimeSeriesBoundary.H',['../REMORA__NCTimeSeriesBoundary_8H.html',1,'']]],
  ['remora_5fnctimeseriesriver_2ecpp_171',['REMORA_NCTimeSeriesRiver.cpp',['../REMORA__NCTimeSeriesRiver_8cpp.html',1,'']]],
  ['remora_5fnctimeseriesriver_2eh_172',['REMORA_NCTimeSeriesRiver.H',['../REMORA__NCTimeSeriesRiver_8H.html',1,'']]],
  ['remora_5fparticledata_2eh_173',['REMORA_ParticleData.H',['../REMORA__ParticleData_8H.html',1,'']]],
  ['remora_5fpc_2eh_174',['REMORA_PC.H',['../REMORA__PC_8H.html',1,'']]],
  ['remora_5fpc_5fevolve_2ecpp_175',['REMORA_PC_Evolve.cpp',['../REMORA__PC__Evolve_8cpp.html',1,'']]],
  ['remora_5fpc_5finit_2ecpp_176',['REMORA_PC_Init.cpp',['../REMORA__PC__Init_8cpp.html',1,'']]],
  ['remora_5fpc_5futils_2ecpp_177',['REMORA_PC_Utils.cpp',['../REMORA__PC__Utils_8cpp.html',1,'']]],
  ['remora_5fphysbcfunct_2ecpp_178',['REMORA_PhysBCFunct.cpp',['../REMORA__PhysBCFunct_8cpp.html',1,'']]],
  ['remora_5fphysbcfunct_2eh_179',['REMORA_PhysBCFunct.H',['../REMORA__PhysBCFunct_8H.html',1,'']]],
  ['remora_5fplotfile_2ecpp_180',['REMORA_Plotfile.cpp',['../REMORA__Plotfile_8cpp.html',1,'']]],
  ['remora_5fprestep_2ecpp_181',['REMORA_prestep.cpp',['../REMORA__prestep_8cpp.html',1,'']]],
  ['remora_5fprestep_5fdiffusion_2ecpp_182',['REMORA_prestep_diffusion.cpp',['../REMORA__prestep__diffusion_8cpp.html',1,'']]],
  ['remora_5fprestep_5ft_5fadvection_2ecpp_183',['REMORA_prestep_t_advection.cpp',['../REMORA__prestep__t__advection_8cpp.html',1,'']]],
  ['remora_5fprob_5fcommon_2eh_184',['REMORA_prob_common.H',['../REMORA__prob__common_8H.html',1,'']]],
  ['remora_5fprsgrd_2ecpp_185',['REMORA_prsgrd.cpp',['../REMORA__prsgrd_8cpp.html',1,'']]],
  ['remora_5freadfrominitnetcdf_2ecpp_186',['REMORA_ReadFromInitNetcdf.cpp',['../REMORA__ReadFromInitNetcdf_8cpp.html',1,'']]],
  ['remora_5fref_5fdatenum_187',['remora_ref_datenum',['../REMORA__DateClock_8H.html#aa1419b324052faecd7b3addf3744ac95',1,'REMORA_DateClock.H']]],
  ['remora_5frho_5feos_2ecpp_188',['REMORA_rho_eos.cpp',['../REMORA__rho__eos_8cpp.html',1,'']]],
  ['remora_5frhs_5ft_5f3d_2ecpp_189',['REMORA_rhs_t_3d.cpp',['../REMORA__rhs__t__3d_8cpp.html',1,'']]],
  ['remora_5frhs_5fuv_5f2d_2ecpp_190',['REMORA_rhs_uv_2d.cpp',['../REMORA__rhs__uv__2d_8cpp.html',1,'']]],
  ['remora_5frhs_5fuv_5f3d_2ecpp_191',['REMORA_rhs_uv_3d.cpp',['../REMORA__rhs__uv__3d_8cpp.html',1,'']]],
  ['remora_5fscale_5frhs_5fvars_2ecpp_192',['REMORA_scale_rhs_vars.cpp',['../REMORA__scale__rhs__vars_8cpp.html',1,'']]],
  ['remora_5fset_5fweights_2ecpp_193',['REMORA_set_weights.cpp',['../REMORA__set__weights_8cpp.html',1,'']]],
  ['remora_5fsetplotvars_2ecpp_194',['REMORA_SetPlotVars.cpp',['../REMORA__SetPlotVars_8cpp.html',1,'']]],
  ['remora_5fsetup_5fstep_2ecpp_195',['REMORA_setup_step.cpp',['../REMORA__setup__step_8cpp.html',1,'']]],
  ['remora_5fsumiq_2ecpp_196',['REMORA_SumIQ.cpp',['../REMORA__SumIQ_8cpp.html',1,'']]],
  ['remora_5ft3dmix_2ecpp_197',['REMORA_t3dmix.cpp',['../REMORA__t3dmix_8cpp.html',1,'']]],
  ['remora_5ftagging_2ecpp_198',['REMORA_Tagging.cpp',['../REMORA__Tagging_8cpp.html',1,'']]],
  ['remora_5ftime_5fref_5fis_5frepresentable_199',['remora_time_ref_is_representable',['../REMORA__DateClock_8H.html#a81dc420dc7b991c2386049c98f8401b6',1,'REMORA_DateClock.H']]],
  ['remora_5ftime_5fref_5fis_5fvalid_200',['remora_time_ref_is_valid',['../REMORA__DateClock_8H.html#a1c6c0466fd9d5141a6ee36b9ea8021e1',1,'REMORA_DateClock.H']]],
  ['remora_5ftimeinterpolateddata_2eh_201',['REMORA_TimeInterpolatedData.H',['../REMORA__TimeInterpolatedData_8H.html',1,'']]],
  ['remora_5ftimestep_2ecpp_202',['REMORA_TimeStep.cpp',['../REMORA__TimeStep_8cpp.html',1,'']]],
  ['remora_5ftimestepml_2ecpp_203',['REMORA_TimeStepML.cpp',['../REMORA__TimeStepML_8cpp.html',1,'']]],
  ['remora_5ftracers_2ecpp_204',['REMORA_Tracers.cpp',['../REMORA__Tracers_8cpp.html',1,'']]],
  ['remora_5fupdate_5fmassflux_5f3d_2ecpp_205',['REMORA_update_massflux_3d.cpp',['../REMORA__update__massflux__3d_8cpp.html',1,'']]],
  ['remora_5fuv3dmix_2ecpp_206',['REMORA_uv3dmix.cpp',['../REMORA__uv3dmix_8cpp.html',1,'']]],
  ['remora_5fvert_5fmean_5f3d_2ecpp_207',['REMORA_vert_mean_3d.cpp',['../REMORA__vert__mean__3d_8cpp.html',1,'']]],
  ['remora_5fvert_5fvisc_5f3d_2ecpp_208',['REMORA_vert_visc_3d.cpp',['../REMORA__vert__visc__3d_8cpp.html',1,'']]],
  ['remora_5fwritejobinfo_2ecpp_209',['REMORA_writeJobInfo.cpp',['../REMORA__writeJobInfo_8cpp.html',1,'']]],
  ['remora_5fyearday_210',['remora_yearday',['../REMORA__DateClock_8H.html#a0da920df23b0c8f5fc12d59ef0ea5c91',1,'REMORA_DateClock.H']]],
  ['remorabctype_211',['REMORABCType',['../namespaceREMORABCType.html',1,'']]],
  ['remorabiology_212',['REMORABiology',['../namespaceREMORABiology.html',1,'']]],
  ['remorabiology_3a_3afennel_213',['Fennel',['../namespaceREMORABiology_1_1Fennel.html',1,'REMORABiology']]],
  ['remorafillpatcher_214',['remorafillpatcher',['../classREMORAFillPatcher.html',1,'REMORAFillPatcher'],['../classREMORAFillPatcher.html#a6b50eb792ad69c394ccc6d1b5214dd96',1,'REMORAFillPatcher::REMORAFillPatcher()']]],
  ['remoraphysbcfunct_215',['remoraphysbcfunct',['../classREMORAPhysBCFunct.html#aa0f07ffec53c799425bf7cbc0b7dcf3b',1,'REMORAPhysBCFunct::REMORAPhysBCFunct()'],['../classREMORAPhysBCFunct.html',1,'REMORAPhysBCFunct']]],
  ['resize_5fstuff_216',['resize_stuff',['../classREMORA.html#aa91decb04550c58b177e6a18b9d70f0d',1,'REMORA']]],
  ['restart_217',['restart',['../classREMORA.html#af82928444cae433cc744c0cf7427e8eb',1,'REMORA']]],
  ['restart_5fchkfile_218',['restart_chkfile',['../classREMORA.html#ae376daabb97c474de25b283de6bd985d',1,'REMORA']]],
  ['rho0_219',['rho0',['../namespacemod__scalars.html#a96b32043ef463cc78050b6d20bb0b9db',1,'mod_scalars::rho0'],['../REMORA__InitAnalyticSMFlux__ParticlesOverSeamount_8H.html#ab8e36533c29290d98a91375f7bdbf726',1,'rho0:&#160;REMORA_InitAnalyticSMFlux_ParticlesOverSeamount.H'],['../structSolverChoice.html#a87396b485f47a76010673143372cca17',1,'SolverChoice::rho0']]],
  ['rho_5feos_220',['rho_eos',['../classREMORA.html#a2b8ea8e7b1db929b8a9c3c8180ee0341',1,'REMORA']]],
  ['rhow_221',['rhow',['../REMORA__Constants_8H.html#aac834cc142fec1b6d8408a0c4819e015',1,'REMORA_Constants.H']]],
  ['rhs_5ft_5f3d_222',['rhs_t_3d',['../classREMORA.html#aa1ca3ce8bd22448b73a7e862b8bb00fd',1,'REMORA']]],
  ['rhs_5fuv_5f2d_223',['rhs_uv_2d',['../classREMORA.html#a84a902c6ed5d0956e188d21c2a864e28',1,'REMORA']]],
  ['rhs_5fuv_5f3d_224',['rhs_uv_3d',['../classREMORA.html#a436da7dba62c2b88911f3a6a70d49925',1,'REMORA']]],
  ['riv_5ftime_5fvarname_225',['riv_time_varname',['../classREMORA.html#a02bcb7acf0e5a7de3c70f29027e6e278',1,'REMORA']]],
  ['river_5fdirection_226',['river_direction',['../classREMORA.html#ab64ce46b4e42cdd5a5804f2eee9b4b63',1,'REMORA']]],
  ['river_5fdon_227',['river_don',['../structREMORABiology_1_1FennelParameters.html#ab061506ec24b92abd51c769807eed025',1,'REMORABiology::FennelParameters']]],
  ['river_5fsource_5fcons_228',['river_source_cons',['../classREMORA.html#ac6b0d3e21b4045578c42233d55713775',1,'REMORA']]],
  ['river_5fsource_5ftransport_229',['river_source_transport',['../classREMORA.html#ac94183c2a93ae17dd452df1b32c10adb',1,'REMORA']]],
  ['river_5fsource_5ftransportbar_230',['river_source_transportbar',['../classREMORA.html#a495d8e3b3344e97ce392a99ed7ab9ab0',1,'REMORA']]],
  ['river_5ftimes_231',['river_times',['../classNCTimeSeriesRiver.html#a680130b9ab77e2a7e974fd3d06c22373',1,'NCTimeSeriesRiver']]],
  ['rmask_232',['rmask',['../structmod__grid_1_1t__grid.html#a4bd1f9c110d3ccb19a6cc020a782905d',1,'mod_grid::t_grid']]],
  ['rrx_233',['rrx',['../REMORA__InitAnalyticBathymetry__Upwelling__ML_8H.html#ae51ba4c9a85750213ff0251cc415cf33',1,'REMORA_InitAnalyticBathymetry_Upwelling_ML.H']]],
  ['rry_234',['rry',['../REMORA__InitAnalyticBathymetry__Upwelling__ML_8H.html#a90eb3e53bf0fc4d87f666beea4e94179',1,'REMORA_InitAnalyticBathymetry_Upwelling_ML.H']]],
  ['rtype_235',['RType',['../structncutils_1_1NCDType.html#a079bbf4314ad09362b5c8124670c821f',1,'ncutils::NCDType']]],
  ['running_5fwith_5fcoupling_5fdriver_236',['running_with_coupling_driver',['../classREMORA.html#a13ee4ac976520b8bf4132619ebcb3ad1',1,'REMORA']]]
];
